// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicontract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminRequestStatsInterval.
const (
	AdminRequestStatsIntervalDay  AdminRequestStatsInterval = "day"
	AdminRequestStatsIntervalHour AdminRequestStatsInterval = "hour"
)

// Valid indicates whether the value is a known member of the AdminRequestStatsInterval enum.
func (e AdminRequestStatsInterval) Valid() bool {
	switch e {
	case AdminRequestStatsIntervalDay:
		return true
	case AdminRequestStatsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for AdminRequestTypeCountType.
const (
	Account  AdminRequestTypeCountType = "account"
	Auth     AdminRequestTypeCountType = "auth"
	Other    AdminRequestTypeCountType = "other"
	Sessions AdminRequestTypeCountType = "sessions"
	Snapshot AdminRequestTypeCountType = "snapshot"
	Stats    AdminRequestTypeCountType = "stats"
	Sync     AdminRequestTypeCountType = "sync"
)

// Valid indicates whether the value is a known member of the AdminRequestTypeCountType enum.
func (e AdminRequestTypeCountType) Valid() bool {
	switch e {
	case Account:
		return true
	case Auth:
		return true
	case Other:
		return true
	case Sessions:
		return true
	case Snapshot:
		return true
	case Stats:
		return true
	case Sync:
		return true
	default:
		return false
	}
}

// Defines values for AdminRequestTypeStatsInterval.
const (
	AdminRequestTypeStatsIntervalDay  AdminRequestTypeStatsInterval = "day"
	AdminRequestTypeStatsIntervalHour AdminRequestTypeStatsInterval = "hour"
)

// Valid indicates whether the value is a known member of the AdminRequestTypeStatsInterval enum.
func (e AdminRequestTypeStatsInterval) Valid() bool {
	switch e {
	case AdminRequestTypeStatsIntervalDay:
		return true
	case AdminRequestTypeStatsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for AuthSessionTokenType.
const (
	Bearer AuthSessionTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthSessionTokenType enum.
func (e AuthSessionTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for ChangeEntity.
const (
	ChangeEntitySession ChangeEntity = "session"
	ChangeEntitySolve   ChangeEntity = "solve"
)

// Valid indicates whether the value is a known member of the ChangeEntity enum.
func (e ChangeEntity) Valid() bool {
	switch e {
	case ChangeEntitySession:
		return true
	case ChangeEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for ChangeOperation.
const (
	ChangeOperationDelete ChangeOperation = "delete"
	ChangeOperationUpsert ChangeOperation = "upsert"
)

// Valid indicates whether the value is a known member of the ChangeOperation enum.
func (e ChangeOperation) Valid() bool {
	switch e {
	case ChangeOperationDelete:
		return true
	case ChangeOperationUpsert:
		return true
	default:
		return false
	}
}

// Defines values for Event.
const (
	Megaminx Event = "megaminx"
	N2x2     Event = "2x2"
	N3x3     Event = "3x3"
	N4x4     Event = "4x4"
	N5x5     Event = "5x5"
	Pyraminx Event = "pyraminx"
)

// Valid indicates whether the value is a known member of the Event enum.
func (e Event) Valid() bool {
	switch e {
	case Megaminx:
		return true
	case N2x2:
		return true
	case N3x3:
		return true
	case N4x4:
		return true
	case N5x5:
		return true
	case Pyraminx:
		return true
	default:
		return false
	}
}

// Defines values for MutationEntity.
const (
	MutationEntitySession MutationEntity = "session"
	MutationEntitySolve   MutationEntity = "solve"
)

// Valid indicates whether the value is a known member of the MutationEntity enum.
func (e MutationEntity) Valid() bool {
	switch e {
	case MutationEntitySession:
		return true
	case MutationEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for MutationOperation.
const (
	MutationOperationDelete MutationOperation = "delete"
	MutationOperationUpsert MutationOperation = "upsert"
)

// Valid indicates whether the value is a known member of the MutationOperation enum.
func (e MutationOperation) Valid() bool {
	switch e {
	case MutationOperationDelete:
		return true
	case MutationOperationUpsert:
		return true
	default:
		return false
	}
}

// Defines values for MutationOutcomeStatus.
const (
	Accepted MutationOutcomeStatus = "accepted"
	Conflict MutationOutcomeStatus = "conflict"
	Rejected MutationOutcomeStatus = "rejected"
)

// Valid indicates whether the value is a known member of the MutationOutcomeStatus enum.
func (e MutationOutcomeStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Conflict:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for SessionKind.
const (
	SessionKindAutomatic SessionKind = "automatic"
	SessionKindManual    SessionKind = "manual"
)

// Valid indicates whether the value is a known member of the SessionKind enum.
func (e SessionKind) Valid() bool {
	switch e {
	case SessionKindAutomatic:
		return true
	case SessionKindManual:
		return true
	default:
		return false
	}
}

// Defines values for SessionInputKind.
const (
	SessionInputKindAutomatic SessionInputKind = "automatic"
	SessionInputKindManual    SessionInputKind = "manual"
)

// Valid indicates whether the value is a known member of the SessionInputKind enum.
func (e SessionInputKind) Valid() bool {
	switch e {
	case SessionInputKindAutomatic:
		return true
	case SessionInputKindManual:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotRequestEntity.
const (
	SnapshotRequestEntitySession SnapshotRequestEntity = "session"
	SnapshotRequestEntitySolve   SnapshotRequestEntity = "solve"
)

// Valid indicates whether the value is a known member of the SnapshotRequestEntity enum.
func (e SnapshotRequestEntity) Valid() bool {
	switch e {
	case SnapshotRequestEntitySession:
		return true
	case SnapshotRequestEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotResponseNextEntity.
const (
	SnapshotResponseNextEntitySession SnapshotResponseNextEntity = "session"
	SnapshotResponseNextEntitySolve   SnapshotResponseNextEntity = "solve"
)

// Valid indicates whether the value is a known member of the SnapshotResponseNextEntity enum.
func (e SnapshotResponseNextEntity) Valid() bool {
	switch e {
	case SnapshotResponseNextEntitySession:
		return true
	case SnapshotResponseNextEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for SolvePenalty.
const (
	SolvePenaltyDnf     SolvePenalty = "dnf"
	SolvePenaltyNone    SolvePenalty = "none"
	SolvePenaltyPlusTwo SolvePenalty = "plus_two"
)

// Valid indicates whether the value is a known member of the SolvePenalty enum.
func (e SolvePenalty) Valid() bool {
	switch e {
	case SolvePenaltyDnf:
		return true
	case SolvePenaltyNone:
		return true
	case SolvePenaltyPlusTwo:
		return true
	default:
		return false
	}
}

// Defines values for SolveInputPenalty.
const (
	SolveInputPenaltyDnf     SolveInputPenalty = "dnf"
	SolveInputPenaltyNone    SolveInputPenalty = "none"
	SolveInputPenaltyPlusTwo SolveInputPenalty = "plus_two"
)

// Valid indicates whether the value is a known member of the SolveInputPenalty enum.
func (e SolveInputPenalty) Valid() bool {
	switch e {
	case SolveInputPenaltyDnf:
		return true
	case SolveInputPenaltyNone:
		return true
	case SolveInputPenaltyPlusTwo:
		return true
	default:
		return false
	}
}

// Defines values for UserUserRole.
const (
	UserUserRoleAdmin UserUserRole = "admin"
	UserUserRoleUser  UserUserRole = "user"
)

// Valid indicates whether the value is a known member of the UserUserRole enum.
func (e UserUserRole) Valid() bool {
	switch e {
	case UserUserRoleAdmin:
		return true
	case UserUserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for Provider.
const (
	ProviderGoogle Provider = "google"
)

// Valid indicates whether the value is a known member of the Provider enum.
func (e Provider) Valid() bool {
	switch e {
	case ProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for StatsInterval.
const (
	StatsIntervalDay  StatsInterval = "day"
	StatsIntervalHour StatsInterval = "hour"
)

// Valid indicates whether the value is a known member of the StatsInterval enum.
func (e StatsInterval) Valid() bool {
	switch e {
	case StatsIntervalDay:
		return true
	case StatsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for GetAdminRequestTypeStatsParamsInterval.
const (
	GetAdminRequestTypeStatsParamsIntervalDay  GetAdminRequestTypeStatsParamsInterval = "day"
	GetAdminRequestTypeStatsParamsIntervalHour GetAdminRequestTypeStatsParamsInterval = "hour"
)

// Valid indicates whether the value is a known member of the GetAdminRequestTypeStatsParamsInterval enum.
func (e GetAdminRequestTypeStatsParamsInterval) Valid() bool {
	switch e {
	case GetAdminRequestTypeStatsParamsIntervalDay:
		return true
	case GetAdminRequestTypeStatsParamsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for GetAdminRequestStatsParamsInterval.
const (
	GetAdminRequestStatsParamsIntervalDay  GetAdminRequestStatsParamsInterval = "day"
	GetAdminRequestStatsParamsIntervalHour GetAdminRequestStatsParamsInterval = "hour"
)

// Valid indicates whether the value is a known member of the GetAdminRequestStatsParamsInterval enum.
func (e GetAdminRequestStatsParamsInterval) Valid() bool {
	switch e {
	case GetAdminRequestStatsParamsIntervalDay:
		return true
	case GetAdminRequestStatsParamsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for FederatedLoginParamsProvider.
const (
	FederatedLoginParamsProviderGoogle FederatedLoginParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the FederatedLoginParamsProvider enum.
func (e FederatedLoginParamsProvider) Valid() bool {
	switch e {
	case FederatedLoginParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for LinkFederatedIdentityParamsProvider.
const (
	LinkFederatedIdentityParamsProviderGoogle LinkFederatedIdentityParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the LinkFederatedIdentityParamsProvider enum.
func (e LinkFederatedIdentityParamsProvider) Valid() bool {
	switch e {
	case LinkFederatedIdentityParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// AdminOverviewStats defines model for AdminOverviewStats.
type AdminOverviewStats struct {
	ActiveUsers24h int64 `json:"active_users_24h"`
	ActiveUsers30d int64 `json:"active_users_30d"`
	ActiveUsers7d  int64 `json:"active_users_7d"`
	NewUsers24h    int64 `json:"new_users_24h"`
	NewUsers30d    int64 `json:"new_users_30d"`
	NewUsers7d     int64 `json:"new_users_7d"`
	TotalDevices   int64 `json:"total_devices"`
	TotalSessions  int64 `json:"total_sessions"`
	TotalSolves    int64 `json:"total_solves"`
	TotalUsers     int64 `json:"total_users"`
	VerifiedUsers  int64 `json:"verified_users"`
}

// AdminRequestStats defines model for AdminRequestStats.
type AdminRequestStats struct {
	From     time.Time                 `json:"from"`
	Interval AdminRequestStatsInterval `json:"interval"`
	Points   []AdminRequestStatsPoint  `json:"points"`
	To       time.Time                 `json:"to"`
}

// AdminRequestStatsInterval defines model for AdminRequestStats.Interval.
type AdminRequestStatsInterval string

// AdminRequestStatsPoint defines model for AdminRequestStatsPoint.
type AdminRequestStatsPoint struct {
	AverageDurationMs float64   `json:"average_duration_ms"`
	Bucket            time.Time `json:"bucket"`
	MaxDurationMs     int64     `json:"max_duration_ms"`
	RequestCount      int64     `json:"request_count"`
	Status2xx         int64     `json:"status_2xx"`
	Status3xx         int64     `json:"status_3xx"`
	Status4xx         int64     `json:"status_4xx"`
	Status5xx         int64     `json:"status_5xx"`
}

// AdminRequestTypeCount defines model for AdminRequestTypeCount.
type AdminRequestTypeCount struct {
	RequestCount int64                     `json:"request_count"`
	Type         AdminRequestTypeCountType `json:"type"`
}

// AdminRequestTypeCountType defines model for AdminRequestTypeCount.Type.
type AdminRequestTypeCountType string

// AdminRequestTypeStats defines model for AdminRequestTypeStats.
type AdminRequestTypeStats struct {
	From     time.Time                     `json:"from"`
	Interval AdminRequestTypeStatsInterval `json:"interval"`
	To       time.Time                     `json:"to"`
	Types    []AdminRequestTypeCount       `json:"types"`
}

// AdminRequestTypeStatsInterval defines model for AdminRequestTypeStats.Interval.
type AdminRequestTypeStatsInterval string

// AuthSession defines model for AuthSession.
type AuthSession struct {
	AccessToken  string               `json:"access_token"`
	ExpiresIn    int64                `json:"expires_in"`
	RefreshToken string               `json:"refresh_token"`
	TokenType    AuthSessionTokenType `json:"token_type"`
	User         User                 `json:"user"`
}

// AuthSessionTokenType defines model for AuthSession.TokenType.
type AuthSessionTokenType string

// Change defines model for Change.
type Change struct {
	ChangedAt time.Time          `json:"changed_at"`
	Cursor    int64              `json:"cursor"`
	Data      Change_Data        `json:"data"`
	Entity    ChangeEntity       `json:"entity"`
	EntityId  openapi_types.UUID `json:"entity_id"`
	Operation ChangeOperation    `json:"operation"`
	Version   int64              `json:"version"`
}

// Change_Data defines model for Change.Data.
type Change_Data struct {
	union json.RawMessage
}

// ChangeEntity defines model for Change.Entity.
type ChangeEntity string

// ChangeOperation defines model for Change.Operation.
type ChangeOperation string

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// CurrentPassword Required if the user already has a password set.
	CurrentPassword *string `json:"current_password,omitempty"`
	NewPassword     string  `json:"new_password"`
}

// ConflictStub defines model for ConflictStub.
type ConflictStub struct {
	Id        openapi_types.UUID `json:"id"`
	UpdatedAt time.Time          `json:"updated_at"`
	Version   int64              `json:"version"`
}

// DeleteStub defines model for DeleteStub.
type DeleteStub struct {
	DeletedAt *time.Time         `json:"deleted_at"`
	Id        openapi_types.UUID `json:"id"`
	Version   int64              `json:"version"`
}

// Device defines model for Device.
type Device struct {
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
	Platform string             `json:"platform"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorLog defines model for ErrorLog.
type ErrorLog struct {
	Code      string    `json:"code"`
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Message   string    `json:"message"`
	Method    string    `json:"method"`
	Route     string    `json:"route"`
	Status    int       `json:"status"`
	UserId    *string   `json:"user_id,omitempty"`
}

// ErrorLogResponse defines model for ErrorLogResponse.
type ErrorLogResponse struct {
	Errors     []ErrorLog `json:"errors"`
	NextCursor *time.Time `json:"next_cursor,omitempty"`
}

// Event defines model for Event.
type Event string

// FederatedInput defines model for FederatedInput.
type FederatedInput struct {
	ClientId     string  `json:"client_id"`
	Code         *string `json:"code,omitempty"`
	CodeVerifier *string `json:"code_verifier,omitempty"`
	IdToken      *string `json:"id_token,omitempty"`
	Nonce        string  `json:"nonce"`
	RedirectUri  *string `json:"redirect_uri,omitempty"`
	union        json.RawMessage
}

// FederatedInput0 defines model for FederatedInput.0.
type FederatedInput0 = interface{}

// FederatedInput1 defines model for FederatedInput.1.
type FederatedInput1 = interface{}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Mutation defines model for Mutation.
type Mutation struct {
	BaseVersion int64              `json:"base_version"`
	Data        *Mutation_Data     `json:"data,omitempty"`
	Entity      MutationEntity     `json:"entity"`
	EntityId    openapi_types.UUID `json:"entity_id"`
	Id          openapi_types.UUID `json:"id"`
	Operation   MutationOperation  `json:"operation"`
}

// Mutation_Data defines model for Mutation.Data.
type Mutation_Data struct {
	union json.RawMessage
}

// MutationEntity defines model for Mutation.Entity.
type MutationEntity string

// MutationOperation defines model for Mutation.Operation.
type MutationOperation string

// MutationOutcome defines model for MutationOutcome.
type MutationOutcome struct {
	Code       *string                  `json:"code,omitempty"`
	Current    *MutationOutcome_Current `json:"current,omitempty"`
	Message    *string                  `json:"message,omitempty"`
	MutationId openapi_types.UUID       `json:"mutation_id"`
	Status     MutationOutcomeStatus    `json:"status"`
	Version    *int64                   `json:"version,omitempty"`
}

// MutationOutcome_Current defines model for MutationOutcome.Current.
type MutationOutcome_Current struct {
	union json.RawMessage
}

// MutationOutcomeStatus defines model for MutationOutcome.Status.
type MutationOutcomeStatus string

// PaginatedSessionsResponse defines model for PaginatedSessionsResponse.
type PaginatedSessionsResponse struct {
	HasMore    *bool             `json:"has_more,omitempty"`
	NextCursor *string           `json:"next_cursor,omitempty"`
	Sessions   *[]SessionSummary `json:"sessions,omitempty"`
}

// PaginatedSolvesResponse defines model for PaginatedSolvesResponse.
type PaginatedSolvesResponse struct {
	HasMore    *bool    `json:"has_more,omitempty"`
	NextCursor *string  `json:"next_cursor,omitempty"`
	Solves     *[]Solve `json:"solves,omitempty"`
}

// PasswordCredentials defines model for PasswordCredentials.
type PasswordCredentials struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RefreshToken defines model for RefreshToken.
type RefreshToken struct {
	RefreshToken string `json:"refresh_token"`
}

// Session defines model for Session.
type Session struct {
	Archived  bool               `json:"archived"`
	DeletedAt *time.Time         `json:"deleted_at,omitempty"`
	EndedAt   *time.Time         `json:"ended_at,omitempty"`
	Event     Event              `json:"event"`
	Id        openapi_types.UUID `json:"id"`
	Kind      SessionKind        `json:"kind"`
	Name      string             `json:"name"`
	StartedAt time.Time          `json:"started_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	Version   int64              `json:"version"`
}

// SessionKind defines model for Session.Kind.
type SessionKind string

// SessionInput defines model for SessionInput.
type SessionInput struct {
	Archived  bool               `json:"archived"`
	EndedAt   *time.Time         `json:"ended_at,omitempty"`
	Event     Event              `json:"event"`
	Id        openapi_types.UUID `json:"id"`
	Kind      SessionInputKind   `json:"kind"`
	Name      string             `json:"name"`
	StartedAt time.Time          `json:"started_at"`
}

// SessionInputKind defines model for SessionInput.Kind.
type SessionInputKind string

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	Archived   *bool               `json:"archived,omitempty"`
	EndedAt    *time.Time          `json:"ended_at,omitempty"`
	Event      *string             `json:"event,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Kind       *string             `json:"kind,omitempty"`
	Name       *string             `json:"name,omitempty"`
	SolveCount *int                `json:"solve_count,omitempty"`
	StartedAt  *time.Time          `json:"started_at,omitempty"`
}

// SnapshotRequest defines model for SnapshotRequest.
type SnapshotRequest struct {
	// AfterId Keyset position for the current entity. Zero UUID for the first page of each entity.
	AfterId *openapi_types.UUID `json:"after_id,omitempty"`

	// Cursor Change-log watermark. 0 on the first page; echo the response cursor on subsequent pages.
	Cursor   *int64                 `json:"cursor,omitempty"`
	Device   Device                 `json:"device"`
	Entity   *SnapshotRequestEntity `json:"entity,omitempty"`
	PageSize *int                   `json:"page_size,omitempty"`
}

// SnapshotRequestEntity defines model for SnapshotRequest.Entity.
type SnapshotRequestEntity string

// SnapshotResponse defines model for SnapshotResponse.
type SnapshotResponse struct {
	// Cursor Stable change-log watermark to use as the initial sync cursor once bootstrap completes.
	Cursor      int64                       `json:"cursor"`
	HasMore     bool                        `json:"has_more"`
	NextAfterId *openapi_types.UUID         `json:"next_after_id,omitempty"`
	NextEntity  *SnapshotResponseNextEntity `json:"next_entity,omitempty"`
	Sessions    *[]Session                  `json:"sessions,omitempty"`
	Solves      *[]Solve                    `json:"solves,omitempty"`
}

// SnapshotResponseNextEntity defines model for SnapshotResponse.NextEntity.
type SnapshotResponseNextEntity string

// Solve defines model for Solve.
type Solve struct {
	DeletedAt  *time.Time          `json:"deleted_at,omitempty"`
	DurationMs int64               `json:"duration_ms"`
	Event      Event               `json:"event"`
	Id         openapi_types.UUID  `json:"id"`
	Penalty    SolvePenalty        `json:"penalty"`
	Scramble   string              `json:"scramble"`
	SessionId  *openapi_types.UUID `json:"session_id,omitempty"`
	SolvedAt   time.Time           `json:"solved_at"`
	UpdatedAt  time.Time           `json:"updated_at"`
	Version    int64               `json:"version"`
}

// SolvePenalty defines model for Solve.Penalty.
type SolvePenalty string

// SolveInput defines model for SolveInput.
type SolveInput struct {
	DurationMs int64               `json:"duration_ms"`
	Event      Event               `json:"event"`
	Id         openapi_types.UUID  `json:"id"`
	Penalty    SolveInputPenalty   `json:"penalty"`
	Scramble   string              `json:"scramble"`
	SessionId  *openapi_types.UUID `json:"session_id,omitempty"`
	SolvedAt   time.Time           `json:"solved_at"`
}

// SolveInputPenalty defines model for SolveInput.Penalty.
type SolveInputPenalty string

// StatsResponse defines model for StatsResponse.
type StatsResponse struct {
	Ao100        *int64  `json:"ao100,omitempty"`
	Ao12         *int64  `json:"ao12,omitempty"`
	Ao5          *int64  `json:"ao5,omitempty"`
	Ao50         *int64  `json:"ao50,omitempty"`
	CountedCount int64   `json:"counted_count"`
	DnfCount     int64   `json:"dnf_count"`
	MaxMs        int64   `json:"max_ms"`
	MeanMs       float64 `json:"mean_ms"`
	MinMs        int64   `json:"min_ms"`
	StddevMs     float64 `json:"stddev_ms"`
	TotalCount   int64   `json:"total_count"`
	TotalMs      int64   `json:"total_ms"`
}

// Status defines model for Status.
type Status struct {
	Status string `json:"status"`
}

// SyncRequest defines model for SyncRequest.
type SyncRequest struct {
	Cursor    int64      `json:"cursor"`
	Device    Device     `json:"device"`
	Limit     *int       `json:"limit,omitempty"`
	Mutations []Mutation `json:"mutations"`
}

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	Changes    []Change          `json:"changes"`
	HasMore    bool              `json:"has_more"`
	NextCursor int64             `json:"next_cursor"`
	Outcomes   []MutationOutcome `json:"outcomes"`
}

// User defines model for User.
type User struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            openapi_types.UUID  `json:"id"`
	UserRole      UserUserRole        `json:"user_role"`
}

// UserUserRole defines model for User.UserRole.
type UserUserRole string

// Provider defines model for Provider.
type Provider string

// StatsFrom defines model for StatsFrom.
type StatsFrom = time.Time

// StatsInterval defines model for StatsInterval.
type StatsInterval string

// StatsTo defines model for StatsTo.
type StatsTo = time.Time

// GetAdminErrorStatsParams defines parameters for GetAdminErrorStats.
type GetAdminErrorStatsParams struct {
	// Before Cursor for pagination - returns errors before this timestamp
	Before *time.Time `form:"before,omitempty" json:"before,omitempty"`
}

// GetAdminRequestTypeStatsParams defines parameters for GetAdminRequestTypeStats.
type GetAdminRequestTypeStatsParams struct {
	From     *StatsFrom                              `form:"from,omitempty" json:"from,omitempty"`
	To       *StatsTo                                `form:"to,omitempty" json:"to,omitempty"`
	Interval *GetAdminRequestTypeStatsParamsInterval `form:"interval,omitempty" json:"interval,omitempty"`
}

// GetAdminRequestTypeStatsParamsInterval defines parameters for GetAdminRequestTypeStats.
type GetAdminRequestTypeStatsParamsInterval string

// GetAdminRequestStatsParams defines parameters for GetAdminRequestStats.
type GetAdminRequestStatsParams struct {
	From     *StatsFrom                          `form:"from,omitempty" json:"from,omitempty"`
	To       *StatsTo                            `form:"to,omitempty" json:"to,omitempty"`
	Interval *GetAdminRequestStatsParamsInterval `form:"interval,omitempty" json:"interval,omitempty"`
}

// GetAdminRequestStatsParamsInterval defines parameters for GetAdminRequestStats.
type GetAdminRequestStatsParamsInterval string

// ResendVerificationJSONBody defines parameters for ResendVerification.
type ResendVerificationJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// VerifyEmailJSONBody defines parameters for VerifyEmail.
type VerifyEmailJSONBody struct {
	Token string `json:"token"`
}

// FederatedLoginParamsProvider defines parameters for FederatedLogin.
type FederatedLoginParamsProvider string

// LinkFederatedIdentityParamsProvider defines parameters for LinkFederatedIdentity.
type LinkFederatedIdentityParamsProvider string

// ForgotPasswordJSONBody defines parameters for ForgotPassword.
type ForgotPasswordJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// ResetPasswordJSONBody defines parameters for ResetPassword.
type ResetPasswordJSONBody struct {
	NewPassword string `json:"new_password"`
	Token       string `json:"token"`
}

// GetV1SessionsParams defines parameters for GetV1Sessions.
type GetV1SessionsParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetV1SessionsIdSolvesParams defines parameters for GetV1SessionsIdSolves.
type GetV1SessionsIdSolvesParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetV1StatsParams defines parameters for GetV1Stats.
type GetV1StatsParams struct {
	Event *string `form:"event,omitempty" json:"event,omitempty"`
}

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody ResendVerificationJSONBody

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody VerifyEmailJSONBody

// FederatedLoginJSONRequestBody defines body for FederatedLogin for application/json ContentType.
type FederatedLoginJSONRequestBody = FederatedInput

// LinkFederatedIdentityJSONRequestBody defines body for LinkFederatedIdentity for application/json ContentType.
type LinkFederatedIdentityJSONRequestBody = FederatedInput

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = PasswordCredentials

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshToken

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody ForgotPasswordJSONBody

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody ResetPasswordJSONBody

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshToken

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = PasswordCredentials

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// PostV1SnapshotJSONRequestBody defines body for PostV1Snapshot for application/json ContentType.
type PostV1SnapshotJSONRequestBody = SnapshotRequest

// SynchronizeJSONRequestBody defines body for Synchronize for application/json ContentType.
type SynchronizeJSONRequestBody = SyncRequest

// AsSession returns the union data inside the Change_Data as a Session
func (t Change_Data) AsSession() (Session, error) {
	var body Session
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSession overwrites any union data inside the Change_Data as the provided Session
func (t *Change_Data) FromSession(v Session) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSession performs a merge with any union data inside the Change_Data, using the provided Session
func (t *Change_Data) MergeSession(v Session) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolve returns the union data inside the Change_Data as a Solve
func (t Change_Data) AsSolve() (Solve, error) {
	var body Solve
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolve overwrites any union data inside the Change_Data as the provided Solve
func (t *Change_Data) FromSolve(v Solve) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolve performs a merge with any union data inside the Change_Data, using the provided Solve
func (t *Change_Data) MergeSolve(v Solve) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeleteStub returns the union data inside the Change_Data as a DeleteStub
func (t Change_Data) AsDeleteStub() (DeleteStub, error) {
	var body DeleteStub
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeleteStub overwrites any union data inside the Change_Data as the provided DeleteStub
func (t *Change_Data) FromDeleteStub(v DeleteStub) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeleteStub performs a merge with any union data inside the Change_Data, using the provided DeleteStub
func (t *Change_Data) MergeDeleteStub(v DeleteStub) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Change_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Change_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsFederatedInput0 returns the union data inside the FederatedInput as a FederatedInput0
func (t FederatedInput) AsFederatedInput0() (FederatedInput0, error) {
	var body FederatedInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFederatedInput0 overwrites any union data inside the FederatedInput as the provided FederatedInput0
func (t *FederatedInput) FromFederatedInput0(v FederatedInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFederatedInput0 performs a merge with any union data inside the FederatedInput, using the provided FederatedInput0
func (t *FederatedInput) MergeFederatedInput0(v FederatedInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFederatedInput1 returns the union data inside the FederatedInput as a FederatedInput1
func (t FederatedInput) AsFederatedInput1() (FederatedInput1, error) {
	var body FederatedInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFederatedInput1 overwrites any union data inside the FederatedInput as the provided FederatedInput1
func (t *FederatedInput) FromFederatedInput1(v FederatedInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFederatedInput1 performs a merge with any union data inside the FederatedInput, using the provided FederatedInput1
func (t *FederatedInput) MergeFederatedInput1(v FederatedInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FederatedInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["client_id"], err = json.Marshal(t.ClientId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'client_id': %w", err)
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if t.CodeVerifier != nil {
		object["code_verifier"], err = json.Marshal(t.CodeVerifier)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code_verifier': %w", err)
		}
	}

	if t.IdToken != nil {
		object["id_token"], err = json.Marshal(t.IdToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id_token': %w", err)
		}
	}

	object["nonce"], err = json.Marshal(t.Nonce)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'nonce': %w", err)
	}

	if t.RedirectUri != nil {
		object["redirect_uri"], err = json.Marshal(t.RedirectUri)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'redirect_uri': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *FederatedInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["client_id"]; found {
		err = json.Unmarshal(raw, &t.ClientId)
		if err != nil {
			return fmt.Errorf("error reading 'client_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["code_verifier"]; found {
		err = json.Unmarshal(raw, &t.CodeVerifier)
		if err != nil {
			return fmt.Errorf("error reading 'code_verifier': %w", err)
		}
	}

	if raw, found := object["id_token"]; found {
		err = json.Unmarshal(raw, &t.IdToken)
		if err != nil {
			return fmt.Errorf("error reading 'id_token': %w", err)
		}
	}

	if raw, found := object["nonce"]; found {
		err = json.Unmarshal(raw, &t.Nonce)
		if err != nil {
			return fmt.Errorf("error reading 'nonce': %w", err)
		}
	}

	if raw, found := object["redirect_uri"]; found {
		err = json.Unmarshal(raw, &t.RedirectUri)
		if err != nil {
			return fmt.Errorf("error reading 'redirect_uri': %w", err)
		}
	}

	return err
}

// AsSessionInput returns the union data inside the Mutation_Data as a SessionInput
func (t Mutation_Data) AsSessionInput() (SessionInput, error) {
	var body SessionInput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionInput overwrites any union data inside the Mutation_Data as the provided SessionInput
func (t *Mutation_Data) FromSessionInput(v SessionInput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionInput performs a merge with any union data inside the Mutation_Data, using the provided SessionInput
func (t *Mutation_Data) MergeSessionInput(v SessionInput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolveInput returns the union data inside the Mutation_Data as a SolveInput
func (t Mutation_Data) AsSolveInput() (SolveInput, error) {
	var body SolveInput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolveInput overwrites any union data inside the Mutation_Data as the provided SolveInput
func (t *Mutation_Data) FromSolveInput(v SolveInput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolveInput performs a merge with any union data inside the Mutation_Data, using the provided SolveInput
func (t *Mutation_Data) MergeSolveInput(v SolveInput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Mutation_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Mutation_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSession returns the union data inside the MutationOutcome_Current as a Session
func (t MutationOutcome_Current) AsSession() (Session, error) {
	var body Session
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSession overwrites any union data inside the MutationOutcome_Current as the provided Session
func (t *MutationOutcome_Current) FromSession(v Session) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSession performs a merge with any union data inside the MutationOutcome_Current, using the provided Session
func (t *MutationOutcome_Current) MergeSession(v Session) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolve returns the union data inside the MutationOutcome_Current as a Solve
func (t MutationOutcome_Current) AsSolve() (Solve, error) {
	var body Solve
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolve overwrites any union data inside the MutationOutcome_Current as the provided Solve
func (t *MutationOutcome_Current) FromSolve(v Solve) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolve performs a merge with any union data inside the MutationOutcome_Current, using the provided Solve
func (t *MutationOutcome_Current) MergeSolve(v Solve) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConflictStub returns the union data inside the MutationOutcome_Current as a ConflictStub
func (t MutationOutcome_Current) AsConflictStub() (ConflictStub, error) {
	var body ConflictStub
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConflictStub overwrites any union data inside the MutationOutcome_Current as the provided ConflictStub
func (t *MutationOutcome_Current) FromConflictStub(v ConflictStub) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConflictStub performs a merge with any union data inside the MutationOutcome_Current, using the provided ConflictStub
func (t *MutationOutcome_Current) MergeConflictStub(v ConflictStub) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MutationOutcome_Current) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MutationOutcome_Current) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FxZk9s28v8qKPz/j/RIczibaJ8cJ87Orrcy5bGzVeuaUmHIloSYBGgAlEdx6btv4eIhghQpS+Oj7BeP",
	"SBzd/etuNBoNfsQxz3LOgCmJZx9xTgTJQIEwv24EX9MEhP6bMjzDOVErHGFGMtC//OsIC3hfUAEJnilR",
	"QIRlvIKM6H7AigzP3uIl58sU8F2E1SbXvaUSlC3xdhvhW0WUfCF4Vk70vgCxqWZa6Hf1URdcZEThGU6I",
	"gieKZoA7B75mCsSapF2DU/++PkECC1KkeoYVLzSHng/3MyGbHl5e867JFB/Px1bLV+acSTCw/CoEN5jE",
	"nClgSv9J8jylMVGUs8mfkjP9rJrm/wUs8Az/36RCe2LfyokdzcySgIwFzfUgeGanQX5mw5zro4d8lmSU",
	"/b4GsabwwTCtn+aC5yAUtYSSWNE1zAsJQs4vrlYNjilTP1xV3GoUliDwNmp2u5wmh3T729BeDD6MJrDq",
	"M5y6qs9g0hRXJJ0nsKYxyFF9JEhJORvZiafrkfMYhgb2WIOgCwrJiE7bumN525izNd4ukjsS3wUtaitn",
	"W4MCqriLSkviO9KsfAS//xNipSVhTOcVvC9Aqg7LWThnOMQ/RJUHm30c5qcinHPqXD5VkMl9TqJF8o3u",
	"j7flyEQIsjG/+Qj/XEfX+XjjIGsu2RE6SI6WqLYbWoMgS5gnhTAOcp411S/hxX1aI5AV2b3V2fsifgdq",
	"OBAZeeicpdsyhGVhHvOCqYF9pCKqkPOLh4dxHS7Hdrga2+HpwA478DtR70qjwWmDiwaFjdmjIOJtdPbp",
	"1OtNDs95EVKpQyCzTyoLJYWyTqfkdMNi/R8juVxx86TyKtI4ighztQIRDj0avlK/3RXmEIY/l0Ma7jfs",
	"g8N8VwVpy3UNc0d26qAgC7W6tXiFIqEYpJwr/g7M2xZL8JBTAXJO2WCnsRAgVz1Dmjdzr3UxZ1KP+DMQ",
	"YUL2Vnu9yO2T5RsZMN0Gc7uUNeho8OlmDMny+YqwJbTFGJvnyZyM8MlxISQXjfbdUk2IMgEzZ/D7As/e",
	"9kvDw72N9rTTscDeVr9ACgpuVXGPt3daJZiialM3IecOcIRNdBG0I9trTptBZlHQJCQcLVyinMr6aYpc",
	"glDaVg1FwWnWILymj/X0DpCSwTrNdYqqSRwuUR3/brW5IVJ+4CJxJh/QokIIYGqeu4Z2v1ff+rxy5CK6",
	"QGoFSCsqIqkAkmzQikhEkO+MJKizkGh1vFmfIaPsJbClWuHZj/u8d6NvkFPOFimNldGWFoMDwS9ybTjj",
	"rOkTcDdEVJDWZg9xWLOGFn9WLwcQ/tZTHmFWpCnWZjVQOMdjtEZtmFG9kzgYRJtX+KiDG69e5xfTQMM8",
	"JUqPttP4arpPGc28ZpraICFOyrxEkxEIP455AsF1KwMpyTL0bteR6BGq9m2SdtpbQjopf8mXI6iMBYw2",
	"Hjp0598tAv1OrXgSfCV4ocKdbHRce1WbTDs3t15oIyF6L+TSeAMUoyaHkjZPSTlvtB+rCoRXPuMU1qTh",
	"gV+JamCbyuBBzQOhQR2/cdJwxAU5W7ssnV9hLx4ucIQvHy5xhK8etA48fXhqxLMkGWV6C5NvhP0ztPq+",
	"gESvkpBcs7wwIxO2cQFLEyEXhd1to+Ybh4eAhAqI1bwQ1KE0d4kVge+2d9GuOaRUr5w0rH/dxtIYN9Si",
	"pDT0knEWhwdu0N9wl4afPf6jZMZPEQLvH0BStWorY8ukOmZx7UJD/7tQZfDVHPyeSJj7JSTkMzLKaKaV",
	"aXq0MNbq0qBY1jV9rCj1tMFsyKvtDU0bAPVh+3uhYp7BmJXFhqefaxvSCC0NxL2rkWNzKJSV1ZRpkDiG",
	"XEFivJGWnvkzdlQce/NRpzfqs80bsqRMu1gnXdm9LK2InGdc1AV0z3kKhAVWmrZEarn6QcuaI+i2yDIi",
	"NsFERg83Ji19Ml7KI4RhnDiFHMSA3Q09F5BomyRpIEkFGaFpQyvsk1A0XN+Z1UPnH6P6Tu18b3TsZ+jd",
	"rr2yKZHXfoXbTSb2p3J2Zmw2D03XnYYS8YquIQmj+0nbKmDJwV19eNQbzJlGwxeDd5QldTeTEVaYDB4p",
	"FM+IonHQtQzeTklFxNj4/9gb7r4goGcTZ+XtRNTgJKo0ZMRWvRE/jNS572oz8phsNJA9iPkl5DSY1bgu",
	"oTo0tPOwdAo+vBRV5zPB46rxSLQl6Q5rOpONZKHK7XUzyfgv2EhQKOeS6idowYVJNrr4D9nQ8wz9FwRH",
	"b95c/1K2WFAhFcrJEhBfICDxyjfG0X5ZVut3kx6bPX2S8iX6QBSIjIh3Z2iKONuZ9O8I4hU3D311CLKD",
	"6rayuJdaGMw2lg2aejLvZRqsP0duWh2879AUzSX9C0I6sWNpjqK7XtS74qguId8qnVFAcUDWSHGdaEZE",
	"GtFSRnWYg/SpYCXeGNA950oqQXKkBaSX7KEyHhDc1dV1f+5R9zgMiEOj3lAu52hRZ/CUohRaUBHMWMdN",
	"UO8rIMjIg131f/zhaqr/7csGnGShzIGRtIk748zmiAs5Vx84jnDCFmH0Y0Gy+3R3ybya/vRDt670amVI",
	"kEYvvq4IrVmw4GVcZ6UmvCoAGB6qVdmbttJ+17vPpHdH04Qg5Iqong0/4efT6dAKS35+Mbjp0+Eth85v",
	"ojlIRlXdJGwxqr0uEhpcuZUBGVFNltERRWFSJQmshw9uqw7HcGp7ZJ9QiukLl5q41GVeMl0KthJancca",
	"NV06XMiT5OBvNyzuqxToqh3Zk4AfGc2mNKPKeSU77HnTwZ4H1c8lM4fHPuWJg9X0a9vn6XQ6NBpyjNXn",
	"7pZqZ3Bsot/hVLtyoEDoNypdOcAmuM3WjxeoT/PvCyvLCaJSCk069wScb1yR1sGJT/PCn8V1bPCH1o/o",
	"g2PB00ZVo36II0x00d3QwxZH6w5p9QmCZ/sS4kJQtbnVWLhzM1Pdpkvxql8vPB///M9rf/nCMLxTCbdS",
	"Krf3IChb8PbWTY8KTNFYB1gR4otFShk8sftivUtbCc7oX6TczD8v7uE1zUAge9JotmmKKi0wXL3UtoKe",
	"3VzX4rgZPj+bnk3doRYjOcUzfHl2fjY1mWa1MsxOVuZocpJSuwdZ2lLl8pjqOsEz/FK/3LlAcjGdHu36",
	"iDseDdwfuRE8BikRlYgYEnUTRZbSeOSNVJDhO/3M82HKqzoZeWXefhZObvUtlxgQYQnSR6v68A8RodMf",
	"mqZthJ9OL7uGL+ktb9p0SGF9PjFWMzGlvpOq2CEojt9AmcJWM+itKw6uX99628rv2ByC1szcHgdpRX2C",
	"BKhCMInshOgeFlwAUisqkQ5XpSJZjqPgbSbbdvyNprsTwtgqIwkA+pJKpVNnAmIuEkhQbTonB43q1XTa",
	"NVsLVd36fFTrURrjfZ3Bte7l3poqDa9Qzu2G9Im7u1p7Nap5qeuESAVmC2D1zNbHG+Mz13Go2iATLcqv",
	"QOquAP9JWbLeK/pWHX7LpEOUV00m1U3KbTSs8Ws+uGl5kfKk9hsWREAxXBtk1EOipeBFDgm63yAndGTc",
	"zrdmx465wcr0XZFKIYS8y3IpYKkjOiSa+qT9TUoUsHjzbehQoVYTE2LrQcGep+VcBkMt/f4PE4jHvuLJ",
	"iednnmxGQXTgTiVYZhHYBmx3L59vWyp1cTSVcnmIHmfkq5nQhxWoFQjEBWJcmRMdd9MLwQOVyi5eFz8d",
	"EjZqKIPAmr3TphtYA+nmVyfx4yA6sGqlq1plCIBH9Am1S1qhK+9aMsjvQI0LcElg5Oqcx7qCftQWvo53",
	"8tF/TGHbjV5Z9fuSL839qXEuvfyaw/bucOz7hLtTlfxlQdvYvXtUD3HVx7LYlLJ3g2B/Sdm7SrRJWZr6",
	"DaB/1c6yeAaRlg8kJ0do6GIaANBYYTdszkhPIetQNeQ3am6XxzI3vuSF6oVLvz8NXo36z0Mtww2CzEqK",
	"BKy5sY9+tn1Z6mTBxZL38P/CvPeK9T3eO0G8NxApARJUf3B+fJxat1VH1URH46LAaN8F1y/KlXlZu6Kt",
	"RwgLXYV3nw7YBl+Kt3o0LF5xVV9QrC+UnzOME7CkUoHoA8u1+MJigcdwk/UcAnL3iND7AorxJnMk0DKo",
	"CvTaWNlb58/KT7LsX5VdW2RHTJAszNcwFkWabsbq5Yhw1FGoy426koDPbR3xG+lU70QW6z4J0oLeTe9X",
	"wceQRQnxpL6U5UVAPs1PRZzINMPfozg0/mutQ21VO1WK8hPAqBf6dmnqH+f+kl17Wxs6drTVMvVTx3a5",
	"UrhnWWTR6vooZ5PdlwqDcYdr7Fc7ufMxxn5EpL/cYU87yzFyPyzehWjykSbbSVVNvR+ua3efsAO25udC",
	"adL7odA95Sbb6JvVheaVzH5NMG0/SQ/sCLoKwAdRAY3wnyDrDGpuuNR64Nudxn/uXq555Fi0dcsjVBri",
	"2hwISdm9utRhvgJXAuG/xtZji+HzvZDG+3Lxz6PwzULkkCwVUVQqGh+q4L+Bsp9qkuVIlSS1WDvV+bYs",
	"34JT6XKtzvSx9bhejBmQu69hRL440exwuUhAmGPRjCt/Y+krLYsx4N9tbQ+x9jZSiNTV/cnZxGjIGTwQ",
	"fafqLOaZ/vjB/wYA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
