// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicontract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthSessionTokenType.
const (
	Bearer AuthSessionTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthSessionTokenType enum.
func (e AuthSessionTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for ChangeEntity.
const (
	ChangeEntitySession ChangeEntity = "session"
	ChangeEntitySolve   ChangeEntity = "solve"
)

// Valid indicates whether the value is a known member of the ChangeEntity enum.
func (e ChangeEntity) Valid() bool {
	switch e {
	case ChangeEntitySession:
		return true
	case ChangeEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for ChangeOperation.
const (
	ChangeOperationDelete ChangeOperation = "delete"
	ChangeOperationUpsert ChangeOperation = "upsert"
)

// Valid indicates whether the value is a known member of the ChangeOperation enum.
func (e ChangeOperation) Valid() bool {
	switch e {
	case ChangeOperationDelete:
		return true
	case ChangeOperationUpsert:
		return true
	default:
		return false
	}
}

// Defines values for Event.
const (
	Megaminx Event = "megaminx"
	N2x2     Event = "2x2"
	N3x3     Event = "3x3"
	N4x4     Event = "4x4"
	N5x5     Event = "5x5"
	Pyraminx Event = "pyraminx"
)

// Valid indicates whether the value is a known member of the Event enum.
func (e Event) Valid() bool {
	switch e {
	case Megaminx:
		return true
	case N2x2:
		return true
	case N3x3:
		return true
	case N4x4:
		return true
	case N5x5:
		return true
	case Pyraminx:
		return true
	default:
		return false
	}
}

// Defines values for MutationEntity.
const (
	MutationEntitySession MutationEntity = "session"
	MutationEntitySolve   MutationEntity = "solve"
)

// Valid indicates whether the value is a known member of the MutationEntity enum.
func (e MutationEntity) Valid() bool {
	switch e {
	case MutationEntitySession:
		return true
	case MutationEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for MutationOperation.
const (
	MutationOperationDelete MutationOperation = "delete"
	MutationOperationUpsert MutationOperation = "upsert"
)

// Valid indicates whether the value is a known member of the MutationOperation enum.
func (e MutationOperation) Valid() bool {
	switch e {
	case MutationOperationDelete:
		return true
	case MutationOperationUpsert:
		return true
	default:
		return false
	}
}

// Defines values for MutationOutcomeStatus.
const (
	Accepted MutationOutcomeStatus = "accepted"
	Conflict MutationOutcomeStatus = "conflict"
	Rejected MutationOutcomeStatus = "rejected"
)

// Valid indicates whether the value is a known member of the MutationOutcomeStatus enum.
func (e MutationOutcomeStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Conflict:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for SessionKind.
const (
	Automatic SessionKind = "automatic"
	Manual    SessionKind = "manual"
)

// Valid indicates whether the value is a known member of the SessionKind enum.
func (e SessionKind) Valid() bool {
	switch e {
	case Automatic:
		return true
	case Manual:
		return true
	default:
		return false
	}
}

// Defines values for SolvePenalty.
const (
	Dnf     SolvePenalty = "dnf"
	None    SolvePenalty = "none"
	PlusTwo SolvePenalty = "plus_two"
)

// Valid indicates whether the value is a known member of the SolvePenalty enum.
func (e SolvePenalty) Valid() bool {
	switch e {
	case Dnf:
		return true
	case None:
		return true
	case PlusTwo:
		return true
	default:
		return false
	}
}

// Defines values for Provider.
const (
	ProviderApple  Provider = "apple"
	ProviderGoogle Provider = "google"
)

// Valid indicates whether the value is a known member of the Provider enum.
func (e Provider) Valid() bool {
	switch e {
	case ProviderApple:
		return true
	case ProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for FederatedLoginParamsProvider.
const (
	FederatedLoginParamsProviderApple  FederatedLoginParamsProvider = "apple"
	FederatedLoginParamsProviderGoogle FederatedLoginParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the FederatedLoginParamsProvider enum.
func (e FederatedLoginParamsProvider) Valid() bool {
	switch e {
	case FederatedLoginParamsProviderApple:
		return true
	case FederatedLoginParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for LinkFederatedIdentityParamsProvider.
const (
	LinkFederatedIdentityParamsProviderApple  LinkFederatedIdentityParamsProvider = "apple"
	LinkFederatedIdentityParamsProviderGoogle LinkFederatedIdentityParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the LinkFederatedIdentityParamsProvider enum.
func (e LinkFederatedIdentityParamsProvider) Valid() bool {
	switch e {
	case LinkFederatedIdentityParamsProviderApple:
		return true
	case LinkFederatedIdentityParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// AuthSession defines model for AuthSession.
type AuthSession struct {
	AccessToken  string               `json:"access_token"`
	ExpiresIn    int64                `json:"expires_in"`
	RefreshToken string               `json:"refresh_token"`
	TokenType    AuthSessionTokenType `json:"token_type"`
	User         User                 `json:"user"`
}

// AuthSessionTokenType defines model for AuthSession.TokenType.
type AuthSessionTokenType string

// Change defines model for Change.
type Change struct {
	ChangedAt time.Time          `json:"changed_at"`
	Cursor    int64              `json:"cursor"`
	Data      Change_Data        `json:"data"`
	Entity    ChangeEntity       `json:"entity"`
	EntityId  openapi_types.UUID `json:"entity_id"`
	Operation ChangeOperation    `json:"operation"`
	Version   int64              `json:"version"`
}

// Change_Data defines model for Change.Data.
type Change_Data struct {
	union json.RawMessage
}

// ChangeEntity defines model for Change.Entity.
type ChangeEntity string

// ChangeOperation defines model for Change.Operation.
type ChangeOperation string

// Device defines model for Device.
type Device struct {
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
	Platform string             `json:"platform"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Event defines model for Event.
type Event string

// FederatedInput defines model for FederatedInput.
type FederatedInput struct {
	ClientId     string  `json:"client_id"`
	Code         *string `json:"code,omitempty"`
	CodeVerifier *string `json:"code_verifier,omitempty"`
	IdToken      *string `json:"id_token,omitempty"`
	Nonce        string  `json:"nonce"`
	RedirectUri  *string `json:"redirect_uri,omitempty"`
	union        json.RawMessage
}

// FederatedInput0 defines model for FederatedInput.0.
type FederatedInput0 = interface{}

// FederatedInput1 defines model for FederatedInput.1.
type FederatedInput1 = interface{}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Mutation defines model for Mutation.
type Mutation struct {
	BaseVersion int64              `json:"base_version"`
	Data        *Mutation_Data     `json:"data,omitempty"`
	Entity      MutationEntity     `json:"entity"`
	EntityId    openapi_types.UUID `json:"entity_id"`
	Id          openapi_types.UUID `json:"id"`
	Operation   MutationOperation  `json:"operation"`
}

// Mutation_Data defines model for Mutation.Data.
type Mutation_Data struct {
	union json.RawMessage
}

// MutationEntity defines model for Mutation.Entity.
type MutationEntity string

// MutationOperation defines model for Mutation.Operation.
type MutationOperation string

// MutationOutcome defines model for MutationOutcome.
type MutationOutcome struct {
	Code       *string                  `json:"code,omitempty"`
	Current    *MutationOutcome_Current `json:"current,omitempty"`
	Message    *string                  `json:"message,omitempty"`
	MutationId openapi_types.UUID       `json:"mutation_id"`
	Status     MutationOutcomeStatus    `json:"status"`
	Version    *int64                   `json:"version,omitempty"`
}

// MutationOutcome_Current defines model for MutationOutcome.Current.
type MutationOutcome_Current struct {
	union json.RawMessage
}

// MutationOutcomeStatus defines model for MutationOutcome.Status.
type MutationOutcomeStatus string

// PasswordCredentials defines model for PasswordCredentials.
type PasswordCredentials struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RefreshToken defines model for RefreshToken.
type RefreshToken struct {
	RefreshToken string `json:"refresh_token"`
}

// Session defines model for Session.
type Session struct {
	Archived  bool               `json:"archived"`
	DeletedAt *time.Time         `json:"deleted_at,omitempty"`
	EndedAt   *time.Time         `json:"ended_at,omitempty"`
	Event     Event              `json:"event"`
	Id        openapi_types.UUID `json:"id"`
	Kind      SessionKind        `json:"kind"`
	Name      string             `json:"name"`
	StartedAt time.Time          `json:"started_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	Version   int64              `json:"version"`
}

// SessionKind defines model for Session.Kind.
type SessionKind string

// Solve defines model for Solve.
type Solve struct {
	DeletedAt  *time.Time          `json:"deleted_at,omitempty"`
	DurationMs int64               `json:"duration_ms"`
	Event      Event               `json:"event"`
	Id         openapi_types.UUID  `json:"id"`
	Penalty    SolvePenalty        `json:"penalty"`
	Scramble   string              `json:"scramble"`
	SessionId  *openapi_types.UUID `json:"session_id,omitempty"`
	SolvedAt   time.Time           `json:"solved_at"`
	UpdatedAt  time.Time           `json:"updated_at"`
	Version    int64               `json:"version"`
}

// SolvePenalty defines model for Solve.Penalty.
type SolvePenalty string

// Status defines model for Status.
type Status struct {
	Status string `json:"status"`
}

// SyncRequest defines model for SyncRequest.
type SyncRequest struct {
	Cursor    int64      `json:"cursor"`
	Device    Device     `json:"device"`
	Limit     *int       `json:"limit,omitempty"`
	Mutations []Mutation `json:"mutations"`
}

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	Changes    []Change          `json:"changes"`
	HasMore    bool              `json:"has_more"`
	NextCursor int64             `json:"next_cursor"`
	Outcomes   []MutationOutcome `json:"outcomes"`
}

// User defines model for User.
type User struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            openapi_types.UUID  `json:"id"`
}

// Provider defines model for Provider.
type Provider string

// ResendVerificationJSONBody defines parameters for ResendVerification.
type ResendVerificationJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// VerifyEmailParams defines parameters for VerifyEmail.
type VerifyEmailParams struct {
	Token string `form:"token" json:"token"`
}

// FederatedLoginParamsProvider defines parameters for FederatedLogin.
type FederatedLoginParamsProvider string

// LinkFederatedIdentityParamsProvider defines parameters for LinkFederatedIdentity.
type LinkFederatedIdentityParamsProvider string

// ForgotPasswordJSONBody defines parameters for ForgotPassword.
type ForgotPasswordJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// ResetPasswordJSONBody defines parameters for ResetPassword.
type ResetPasswordJSONBody struct {
	NewPassword string `json:"new_password"`
	Token       string `json:"token"`
}

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody ResendVerificationJSONBody

// FederatedLoginJSONRequestBody defines body for FederatedLogin for application/json ContentType.
type FederatedLoginJSONRequestBody = FederatedInput

// LinkFederatedIdentityJSONRequestBody defines body for LinkFederatedIdentity for application/json ContentType.
type LinkFederatedIdentityJSONRequestBody = FederatedInput

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = PasswordCredentials

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshToken

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody ForgotPasswordJSONBody

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody ResetPasswordJSONBody

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshToken

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = PasswordCredentials

// SynchronizeJSONRequestBody defines body for Synchronize for application/json ContentType.
type SynchronizeJSONRequestBody = SyncRequest

// AsSession returns the union data inside the Change_Data as a Session
func (t Change_Data) AsSession() (Session, error) {
	var body Session
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSession overwrites any union data inside the Change_Data as the provided Session
func (t *Change_Data) FromSession(v Session) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSession performs a merge with any union data inside the Change_Data, using the provided Session
func (t *Change_Data) MergeSession(v Session) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolve returns the union data inside the Change_Data as a Solve
func (t Change_Data) AsSolve() (Solve, error) {
	var body Solve
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolve overwrites any union data inside the Change_Data as the provided Solve
func (t *Change_Data) FromSolve(v Solve) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolve performs a merge with any union data inside the Change_Data, using the provided Solve
func (t *Change_Data) MergeSolve(v Solve) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Change_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Change_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsFederatedInput0 returns the union data inside the FederatedInput as a FederatedInput0
func (t FederatedInput) AsFederatedInput0() (FederatedInput0, error) {
	var body FederatedInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFederatedInput0 overwrites any union data inside the FederatedInput as the provided FederatedInput0
func (t *FederatedInput) FromFederatedInput0(v FederatedInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFederatedInput0 performs a merge with any union data inside the FederatedInput, using the provided FederatedInput0
func (t *FederatedInput) MergeFederatedInput0(v FederatedInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFederatedInput1 returns the union data inside the FederatedInput as a FederatedInput1
func (t FederatedInput) AsFederatedInput1() (FederatedInput1, error) {
	var body FederatedInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFederatedInput1 overwrites any union data inside the FederatedInput as the provided FederatedInput1
func (t *FederatedInput) FromFederatedInput1(v FederatedInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFederatedInput1 performs a merge with any union data inside the FederatedInput, using the provided FederatedInput1
func (t *FederatedInput) MergeFederatedInput1(v FederatedInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FederatedInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["client_id"], err = json.Marshal(t.ClientId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'client_id': %w", err)
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if t.CodeVerifier != nil {
		object["code_verifier"], err = json.Marshal(t.CodeVerifier)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code_verifier': %w", err)
		}
	}

	if t.IdToken != nil {
		object["id_token"], err = json.Marshal(t.IdToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id_token': %w", err)
		}
	}

	object["nonce"], err = json.Marshal(t.Nonce)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'nonce': %w", err)
	}

	if t.RedirectUri != nil {
		object["redirect_uri"], err = json.Marshal(t.RedirectUri)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'redirect_uri': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *FederatedInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["client_id"]; found {
		err = json.Unmarshal(raw, &t.ClientId)
		if err != nil {
			return fmt.Errorf("error reading 'client_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["code_verifier"]; found {
		err = json.Unmarshal(raw, &t.CodeVerifier)
		if err != nil {
			return fmt.Errorf("error reading 'code_verifier': %w", err)
		}
	}

	if raw, found := object["id_token"]; found {
		err = json.Unmarshal(raw, &t.IdToken)
		if err != nil {
			return fmt.Errorf("error reading 'id_token': %w", err)
		}
	}

	if raw, found := object["nonce"]; found {
		err = json.Unmarshal(raw, &t.Nonce)
		if err != nil {
			return fmt.Errorf("error reading 'nonce': %w", err)
		}
	}

	if raw, found := object["redirect_uri"]; found {
		err = json.Unmarshal(raw, &t.RedirectUri)
		if err != nil {
			return fmt.Errorf("error reading 'redirect_uri': %w", err)
		}
	}

	return err
}

// AsSession returns the union data inside the Mutation_Data as a Session
func (t Mutation_Data) AsSession() (Session, error) {
	var body Session
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSession overwrites any union data inside the Mutation_Data as the provided Session
func (t *Mutation_Data) FromSession(v Session) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSession performs a merge with any union data inside the Mutation_Data, using the provided Session
func (t *Mutation_Data) MergeSession(v Session) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolve returns the union data inside the Mutation_Data as a Solve
func (t Mutation_Data) AsSolve() (Solve, error) {
	var body Solve
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolve overwrites any union data inside the Mutation_Data as the provided Solve
func (t *Mutation_Data) FromSolve(v Solve) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolve performs a merge with any union data inside the Mutation_Data, using the provided Solve
func (t *Mutation_Data) MergeSolve(v Solve) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Mutation_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Mutation_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSession returns the union data inside the MutationOutcome_Current as a Session
func (t MutationOutcome_Current) AsSession() (Session, error) {
	var body Session
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSession overwrites any union data inside the MutationOutcome_Current as the provided Session
func (t *MutationOutcome_Current) FromSession(v Session) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSession performs a merge with any union data inside the MutationOutcome_Current, using the provided Session
func (t *MutationOutcome_Current) MergeSession(v Session) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolve returns the union data inside the MutationOutcome_Current as a Solve
func (t MutationOutcome_Current) AsSolve() (Solve, error) {
	var body Solve
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolve overwrites any union data inside the MutationOutcome_Current as the provided Solve
func (t *MutationOutcome_Current) FromSolve(v Solve) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolve performs a merge with any union data inside the MutationOutcome_Current, using the provided Solve
func (t *MutationOutcome_Current) MergeSolve(v Solve) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MutationOutcome_Current) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MutationOutcome_Current) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpbb+O4Ff4rAttHbezcBrt+m0132hQpNkhm24fAMBjp2OJGIhWScuwG+u8Fb7qZki+1s9NB82SJFM85",
	"37kf5h1FLMsZBSoFmryjHHOcgQSun+45W5IYuPpNKJqgHMsEhYjiDNSTWw4Rh9eCcIjRRPICQiSiBDKs",
	"vgNaZGjyhBaMLVJAIcJ5ngKahkiuc3WKkJzQBSrLUh0jckYFaOq/cM406YhRCVSqn+pjEmFJGB39LhhV",
	"72paf+YwRxP0p1Et1MisipE5TVOJQUSc5OoQNDFkAkcZqQ32G3Xk50ImjyAEMbRyznLgkhgOcRSBEDPJ",
	"XkCvdiQKEaxywkHMiF6eM55hiSaIUPnpClUIECphARxpAOYcRDJwpF6ZmdcaGqFO/Bkw14rY2F8Io78h",
	"bH5Tewz+To1PbeG6nLX4aMlpKdb6Zc+/QyQVKzcJpgvYhDHS7+MZli2UYizhB0ky8IkVFVwY69gB1RhL",
	"bR+Mwq9zNHkaRsOpuwy37GPpElA5VXqmksh109yFPSREQm+bemQwX81I3BKjKEjsk1ghhqW1Q0emyAVw",
	"iZRNpyD9ZJbAnfluxapjAxblSsAmz02OaiIW7LCpVJ8t/AWWJPLYwo5gmAj0jjK8ugO6kAmanF+MPRvz",
	"FEt1Wmfz1ebejuiaribTOMQnSRWm2oKA/3XEYvD6dQZC4IVvrasTdUK9f5Olzn7DiJfzpY2qzpouVhco",
	"RJerSxSiq5Wyj+vVtaa1wBmhKwXFmpufPkv7ArGyCIhvaV6YeE3X1uPa2NowMlU+5hGOQ0w4RHJWcKJs",
	"icUwWwInc6JCSzkNu6imBKi0nrQZK/owb5/r21Fx6lukjEb+g1v8t+xZy7NFwZUwjoRPeX8DnCpL7hqY",
	"kFgWYrsZ2X2+o/9RyCrQtA9/xkID1htPMkJJpoxp/N3G4dOGa18U2hp8W2oZ0uivhYxYBnuEpajg3EaJ",
	"k2mtP/SFKLOc76qd2vwd5qqOySXEOqwoQPTPiNF5SiJ57IzZ5DcccrJ7LMQb4/ENh1jpFafCk0QyTNIW",
	"G+aNL9HZ8zay4o/aK6vnrYnPUagO9HH/YKrBry42ttneVsV2KLa3+8j1V+A8SsgSmnH/mbEUMNXxRnvZ",
	"DoXlk2MtRLRIU2RiSXzwpy6xDjYketPuAeWF0Lhp1xmmBVaKwoVkGZYk8tryzpWSkJjLPavwIlfL+31z",
	"aPoYqM8M3hailiRhbSHNGrXBt9fcdGzaMLb/ypziwoTrWSb8ouOVEf3HT1dj9bctmZ7EyHKgOG1nUMqo",
	"qYELMZNvTCUvOveamog4zp5T2Ki1f/rk2218ejCw+4DUefx/y0ybuq8xborSAK82593ttUp6R68FH9c0",
	"eoDXAoT0VA39TfiWQrDq/oaM1/aIZYhSkhFpzcoce972kHMfFZeLTWMpwXjeEMWq8i21Q96ab67HtRCY",
	"c7zu75OtYE3a/ajaiVPPPGR3ru1cpewyGaIEi1nGOPjTI4WVnO01SGGmftwfUFd4lluArAiEFQptPhsy",
	"+YD9zU67Di6j9ILrCXvKip1iqbeQt1Q7RLwtvICo4ESuHxWStvvSQ77PhWn7zNMXx8Xf//UV2cmlZrcz",
	"EEykzM30k9A5M9msOQVVp6oyNFJxJgzYfJ4SCj/MCRcyEGsaJZxR8m+tzGDOeHBTPMNXkgEPTL8qzhQx",
	"IlX4R/WisvTg8/1tI5xN0PnZ+GxsmySKc4Im6PLs/Gysq06ZaGFHiW5wRykxqXgBpglxbc9tjCboTi12",
	"xsYX4/HRhsa2yfZMje85i0CIgIgAaxbVFokXQsfTtZCQoal65+TggON1ryAPevUPkeQRuIpZAaZxoBp0",
	"1UwGmENgOC5DdD2+7Du+4rear/egsDwf4UImI2366jMw1WzOhBcOtf5P7SCR63K5SUM/M4PjzrAcGAu8",
	"bZHHVcvu7Ue5ocaLo6nRZnqPGm2SDly7G7wlIBPgAeMBZTKQCag1VlAZwIoIKZRqry5+OkS1SpVexeqY",
	"1m/mWqPrX6oOs75serI3TK8F8HV9xVTfPvTdL3W1Nj2hEzUvg3w3SUquwIV17VC2yA0iDiqwasgNQ0eA",
	"fO7GraN3dxVX9vtUNZy9Ywt9T9OB38dQvWVU3QUahA9zxSFwO8PjnRzrw1TbSo9Oq0ab5ztrU+0+lrul",
	"hL7spPY7Ql9qaONqlvgdaP9qs4xxAgYKH+dvJ9SQq9I0hs367EnfUgwpUHthv9qsk54Ca9/o8Tt1t8tj",
	"uRtbMHOj1asutX4afbWGrYd6hj0k0Bk14LBk2j+GxXYz4NGc8QUbkP+LXneG9f9i7QTF2o6aUqW1HK6s",
	"j68nCm+zwy8g7D+TbJ9TuWqwRe4wLX9YKHNYB/YfIk5fFtrrlCEbMBu+lWj1Ybp4YLKZUEwsFH9kGcdh",
	"QYS0M6seZdkd31gt8BFhsjkACOwtcfBaQLG/yxxJaVn/LOqvIG/MZbkeQp7Qyu2/623AZcm7zLGvXe9R",
	"zloCFSxiTaN+E36sxodwIitu3lJ8cMhpjfI9SnET8MCNtnUCYDwGDnHAIWMSAjfrPsCoT1gP72gNWvnT",
	"0nzBl66jLHhq585iMtIWcgYrnOUpnEUsQ+W0/E8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
