// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicontract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminErrorStatsInterval.
const (
	AdminErrorStatsIntervalDay  AdminErrorStatsInterval = "day"
	AdminErrorStatsIntervalHour AdminErrorStatsInterval = "hour"
)

// Valid indicates whether the value is a known member of the AdminErrorStatsInterval enum.
func (e AdminErrorStatsInterval) Valid() bool {
	switch e {
	case AdminErrorStatsIntervalDay:
		return true
	case AdminErrorStatsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for AdminRequestStatsInterval.
const (
	AdminRequestStatsIntervalDay  AdminRequestStatsInterval = "day"
	AdminRequestStatsIntervalHour AdminRequestStatsInterval = "hour"
)

// Valid indicates whether the value is a known member of the AdminRequestStatsInterval enum.
func (e AdminRequestStatsInterval) Valid() bool {
	switch e {
	case AdminRequestStatsIntervalDay:
		return true
	case AdminRequestStatsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for AdminRequestTypeCountType.
const (
	Account  AdminRequestTypeCountType = "account"
	Auth     AdminRequestTypeCountType = "auth"
	Other    AdminRequestTypeCountType = "other"
	Sessions AdminRequestTypeCountType = "sessions"
	Snapshot AdminRequestTypeCountType = "snapshot"
	Stats    AdminRequestTypeCountType = "stats"
	Sync     AdminRequestTypeCountType = "sync"
)

// Valid indicates whether the value is a known member of the AdminRequestTypeCountType enum.
func (e AdminRequestTypeCountType) Valid() bool {
	switch e {
	case Account:
		return true
	case Auth:
		return true
	case Other:
		return true
	case Sessions:
		return true
	case Snapshot:
		return true
	case Stats:
		return true
	case Sync:
		return true
	default:
		return false
	}
}

// Defines values for AdminRequestTypeStatsInterval.
const (
	AdminRequestTypeStatsIntervalDay  AdminRequestTypeStatsInterval = "day"
	AdminRequestTypeStatsIntervalHour AdminRequestTypeStatsInterval = "hour"
)

// Valid indicates whether the value is a known member of the AdminRequestTypeStatsInterval enum.
func (e AdminRequestTypeStatsInterval) Valid() bool {
	switch e {
	case AdminRequestTypeStatsIntervalDay:
		return true
	case AdminRequestTypeStatsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for AuthSessionTokenType.
const (
	Bearer AuthSessionTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthSessionTokenType enum.
func (e AuthSessionTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for ChangeEntity.
const (
	ChangeEntitySession ChangeEntity = "session"
	ChangeEntitySolve   ChangeEntity = "solve"
)

// Valid indicates whether the value is a known member of the ChangeEntity enum.
func (e ChangeEntity) Valid() bool {
	switch e {
	case ChangeEntitySession:
		return true
	case ChangeEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for ChangeOperation.
const (
	ChangeOperationDelete ChangeOperation = "delete"
	ChangeOperationUpsert ChangeOperation = "upsert"
)

// Valid indicates whether the value is a known member of the ChangeOperation enum.
func (e ChangeOperation) Valid() bool {
	switch e {
	case ChangeOperationDelete:
		return true
	case ChangeOperationUpsert:
		return true
	default:
		return false
	}
}

// Defines values for Event.
const (
	Megaminx Event = "megaminx"
	N2x2     Event = "2x2"
	N3x3     Event = "3x3"
	N4x4     Event = "4x4"
	N5x5     Event = "5x5"
	Pyraminx Event = "pyraminx"
)

// Valid indicates whether the value is a known member of the Event enum.
func (e Event) Valid() bool {
	switch e {
	case Megaminx:
		return true
	case N2x2:
		return true
	case N3x3:
		return true
	case N4x4:
		return true
	case N5x5:
		return true
	case Pyraminx:
		return true
	default:
		return false
	}
}

// Defines values for MutationEntity.
const (
	MutationEntitySession MutationEntity = "session"
	MutationEntitySolve   MutationEntity = "solve"
)

// Valid indicates whether the value is a known member of the MutationEntity enum.
func (e MutationEntity) Valid() bool {
	switch e {
	case MutationEntitySession:
		return true
	case MutationEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for MutationOperation.
const (
	MutationOperationDelete MutationOperation = "delete"
	MutationOperationUpsert MutationOperation = "upsert"
)

// Valid indicates whether the value is a known member of the MutationOperation enum.
func (e MutationOperation) Valid() bool {
	switch e {
	case MutationOperationDelete:
		return true
	case MutationOperationUpsert:
		return true
	default:
		return false
	}
}

// Defines values for MutationOutcomeStatus.
const (
	Accepted MutationOutcomeStatus = "accepted"
	Conflict MutationOutcomeStatus = "conflict"
	Rejected MutationOutcomeStatus = "rejected"
)

// Valid indicates whether the value is a known member of the MutationOutcomeStatus enum.
func (e MutationOutcomeStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Conflict:
		return true
	case Rejected:
		return true
	default:
		return false
	}
}

// Defines values for SessionKind.
const (
	SessionKindAutomatic SessionKind = "automatic"
	SessionKindManual    SessionKind = "manual"
)

// Valid indicates whether the value is a known member of the SessionKind enum.
func (e SessionKind) Valid() bool {
	switch e {
	case SessionKindAutomatic:
		return true
	case SessionKindManual:
		return true
	default:
		return false
	}
}

// Defines values for SessionInputKind.
const (
	SessionInputKindAutomatic SessionInputKind = "automatic"
	SessionInputKindManual    SessionInputKind = "manual"
)

// Valid indicates whether the value is a known member of the SessionInputKind enum.
func (e SessionInputKind) Valid() bool {
	switch e {
	case SessionInputKindAutomatic:
		return true
	case SessionInputKindManual:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotRequestEntity.
const (
	SnapshotRequestEntitySession SnapshotRequestEntity = "session"
	SnapshotRequestEntitySolve   SnapshotRequestEntity = "solve"
)

// Valid indicates whether the value is a known member of the SnapshotRequestEntity enum.
func (e SnapshotRequestEntity) Valid() bool {
	switch e {
	case SnapshotRequestEntitySession:
		return true
	case SnapshotRequestEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for SnapshotResponseNextEntity.
const (
	SnapshotResponseNextEntitySession SnapshotResponseNextEntity = "session"
	SnapshotResponseNextEntitySolve   SnapshotResponseNextEntity = "solve"
)

// Valid indicates whether the value is a known member of the SnapshotResponseNextEntity enum.
func (e SnapshotResponseNextEntity) Valid() bool {
	switch e {
	case SnapshotResponseNextEntitySession:
		return true
	case SnapshotResponseNextEntitySolve:
		return true
	default:
		return false
	}
}

// Defines values for SolvePenalty.
const (
	SolvePenaltyDnf     SolvePenalty = "dnf"
	SolvePenaltyNone    SolvePenalty = "none"
	SolvePenaltyPlusTwo SolvePenalty = "plus_two"
)

// Valid indicates whether the value is a known member of the SolvePenalty enum.
func (e SolvePenalty) Valid() bool {
	switch e {
	case SolvePenaltyDnf:
		return true
	case SolvePenaltyNone:
		return true
	case SolvePenaltyPlusTwo:
		return true
	default:
		return false
	}
}

// Defines values for SolveInputPenalty.
const (
	SolveInputPenaltyDnf     SolveInputPenalty = "dnf"
	SolveInputPenaltyNone    SolveInputPenalty = "none"
	SolveInputPenaltyPlusTwo SolveInputPenalty = "plus_two"
)

// Valid indicates whether the value is a known member of the SolveInputPenalty enum.
func (e SolveInputPenalty) Valid() bool {
	switch e {
	case SolveInputPenaltyDnf:
		return true
	case SolveInputPenaltyNone:
		return true
	case SolveInputPenaltyPlusTwo:
		return true
	default:
		return false
	}
}

// Defines values for UserUserRole.
const (
	UserUserRoleAdmin UserUserRole = "admin"
	UserUserRoleUser  UserUserRole = "user"
)

// Valid indicates whether the value is a known member of the UserUserRole enum.
func (e UserUserRole) Valid() bool {
	switch e {
	case UserUserRoleAdmin:
		return true
	case UserUserRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for Provider.
const (
	ProviderApple  Provider = "apple"
	ProviderGoogle Provider = "google"
)

// Valid indicates whether the value is a known member of the Provider enum.
func (e Provider) Valid() bool {
	switch e {
	case ProviderApple:
		return true
	case ProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for StatsInterval.
const (
	StatsIntervalDay  StatsInterval = "day"
	StatsIntervalHour StatsInterval = "hour"
)

// Valid indicates whether the value is a known member of the StatsInterval enum.
func (e StatsInterval) Valid() bool {
	switch e {
	case StatsIntervalDay:
		return true
	case StatsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for GetAdminErrorStatsParamsInterval.
const (
	GetAdminErrorStatsParamsIntervalDay  GetAdminErrorStatsParamsInterval = "day"
	GetAdminErrorStatsParamsIntervalHour GetAdminErrorStatsParamsInterval = "hour"
)

// Valid indicates whether the value is a known member of the GetAdminErrorStatsParamsInterval enum.
func (e GetAdminErrorStatsParamsInterval) Valid() bool {
	switch e {
	case GetAdminErrorStatsParamsIntervalDay:
		return true
	case GetAdminErrorStatsParamsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for GetAdminRequestTypeStatsParamsInterval.
const (
	GetAdminRequestTypeStatsParamsIntervalDay  GetAdminRequestTypeStatsParamsInterval = "day"
	GetAdminRequestTypeStatsParamsIntervalHour GetAdminRequestTypeStatsParamsInterval = "hour"
)

// Valid indicates whether the value is a known member of the GetAdminRequestTypeStatsParamsInterval enum.
func (e GetAdminRequestTypeStatsParamsInterval) Valid() bool {
	switch e {
	case GetAdminRequestTypeStatsParamsIntervalDay:
		return true
	case GetAdminRequestTypeStatsParamsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for GetAdminRequestStatsParamsInterval.
const (
	GetAdminRequestStatsParamsIntervalDay  GetAdminRequestStatsParamsInterval = "day"
	GetAdminRequestStatsParamsIntervalHour GetAdminRequestStatsParamsInterval = "hour"
)

// Valid indicates whether the value is a known member of the GetAdminRequestStatsParamsInterval enum.
func (e GetAdminRequestStatsParamsInterval) Valid() bool {
	switch e {
	case GetAdminRequestStatsParamsIntervalDay:
		return true
	case GetAdminRequestStatsParamsIntervalHour:
		return true
	default:
		return false
	}
}

// Defines values for FederatedLoginParamsProvider.
const (
	FederatedLoginParamsProviderApple  FederatedLoginParamsProvider = "apple"
	FederatedLoginParamsProviderGoogle FederatedLoginParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the FederatedLoginParamsProvider enum.
func (e FederatedLoginParamsProvider) Valid() bool {
	switch e {
	case FederatedLoginParamsProviderApple:
		return true
	case FederatedLoginParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// Defines values for LinkFederatedIdentityParamsProvider.
const (
	LinkFederatedIdentityParamsProviderApple  LinkFederatedIdentityParamsProvider = "apple"
	LinkFederatedIdentityParamsProviderGoogle LinkFederatedIdentityParamsProvider = "google"
)

// Valid indicates whether the value is a known member of the LinkFederatedIdentityParamsProvider enum.
func (e LinkFederatedIdentityParamsProvider) Valid() bool {
	switch e {
	case LinkFederatedIdentityParamsProviderApple:
		return true
	case LinkFederatedIdentityParamsProviderGoogle:
		return true
	default:
		return false
	}
}

// AdminErrorStats defines model for AdminErrorStats.
type AdminErrorStats struct {
	From     time.Time               `json:"from"`
	Interval AdminErrorStatsInterval `json:"interval"`
	Points   []AdminErrorStatsPoint  `json:"points"`
	To       time.Time               `json:"to"`
}

// AdminErrorStatsInterval defines model for AdminErrorStats.Interval.
type AdminErrorStatsInterval string

// AdminErrorStatsPoint defines model for AdminErrorStatsPoint.
type AdminErrorStatsPoint struct {
	Bucket       time.Time `json:"bucket"`
	Method       string    `json:"method"`
	RequestCount int64     `json:"request_count"`
	Route        string    `json:"route"`
	StatusCode   int       `json:"status_code"`
}

// AdminOverviewStats defines model for AdminOverviewStats.
type AdminOverviewStats struct {
	ActiveUsers24h int64 `json:"active_users_24h"`
	ActiveUsers30d int64 `json:"active_users_30d"`
	ActiveUsers7d  int64 `json:"active_users_7d"`
	NewUsers24h    int64 `json:"new_users_24h"`
	NewUsers30d    int64 `json:"new_users_30d"`
	NewUsers7d     int64 `json:"new_users_7d"`
	TotalDevices   int64 `json:"total_devices"`
	TotalSessions  int64 `json:"total_sessions"`
	TotalSolves    int64 `json:"total_solves"`
	TotalUsers     int64 `json:"total_users"`
	VerifiedUsers  int64 `json:"verified_users"`
}

// AdminRequestStats defines model for AdminRequestStats.
type AdminRequestStats struct {
	From     time.Time                 `json:"from"`
	Interval AdminRequestStatsInterval `json:"interval"`
	Points   []AdminRequestStatsPoint  `json:"points"`
	To       time.Time                 `json:"to"`
}

// AdminRequestStatsInterval defines model for AdminRequestStats.Interval.
type AdminRequestStatsInterval string

// AdminRequestStatsPoint defines model for AdminRequestStatsPoint.
type AdminRequestStatsPoint struct {
	AverageDurationMs float64   `json:"average_duration_ms"`
	Bucket            time.Time `json:"bucket"`
	MaxDurationMs     int64     `json:"max_duration_ms"`
	RequestCount      int64     `json:"request_count"`
	Status2xx         int64     `json:"status_2xx"`
	Status3xx         int64     `json:"status_3xx"`
	Status4xx         int64     `json:"status_4xx"`
	Status5xx         int64     `json:"status_5xx"`
}

// AdminRequestTypeCount defines model for AdminRequestTypeCount.
type AdminRequestTypeCount struct {
	RequestCount int64                     `json:"request_count"`
	Type         AdminRequestTypeCountType `json:"type"`
}

// AdminRequestTypeCountType defines model for AdminRequestTypeCount.Type.
type AdminRequestTypeCountType string

// AdminRequestTypeStats defines model for AdminRequestTypeStats.
type AdminRequestTypeStats struct {
	From     time.Time                     `json:"from"`
	Interval AdminRequestTypeStatsInterval `json:"interval"`
	To       time.Time                     `json:"to"`
	Types    []AdminRequestTypeCount       `json:"types"`
}

// AdminRequestTypeStatsInterval defines model for AdminRequestTypeStats.Interval.
type AdminRequestTypeStatsInterval string

// AuthSession defines model for AuthSession.
type AuthSession struct {
	AccessToken  string               `json:"access_token"`
	ExpiresIn    int64                `json:"expires_in"`
	RefreshToken string               `json:"refresh_token"`
	TokenType    AuthSessionTokenType `json:"token_type"`
	User         User                 `json:"user"`
}

// AuthSessionTokenType defines model for AuthSession.TokenType.
type AuthSessionTokenType string

// Change defines model for Change.
type Change struct {
	ChangedAt time.Time          `json:"changed_at"`
	Cursor    int64              `json:"cursor"`
	Data      Change_Data        `json:"data"`
	Entity    ChangeEntity       `json:"entity"`
	EntityId  openapi_types.UUID `json:"entity_id"`
	Operation ChangeOperation    `json:"operation"`
	Version   int64              `json:"version"`
}

// Change_Data defines model for Change.Data.
type Change_Data struct {
	union json.RawMessage
}

// ChangeEntity defines model for Change.Entity.
type ChangeEntity string

// ChangeOperation defines model for Change.Operation.
type ChangeOperation string

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// CurrentPassword Required if the user already has a password set.
	CurrentPassword *string `json:"current_password,omitempty"`
	NewPassword     string  `json:"new_password"`
}

// ConflictStub defines model for ConflictStub.
type ConflictStub struct {
	Id        openapi_types.UUID `json:"id"`
	UpdatedAt time.Time          `json:"updated_at"`
	Version   int64              `json:"version"`
}

// DeleteStub defines model for DeleteStub.
type DeleteStub struct {
	DeletedAt *time.Time         `json:"deleted_at"`
	Id        openapi_types.UUID `json:"id"`
	Version   int64              `json:"version"`
}

// Device defines model for Device.
type Device struct {
	Id       openapi_types.UUID `json:"id"`
	Name     string             `json:"name"`
	Platform string             `json:"platform"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

// Event defines model for Event.
type Event string

// FederatedInput defines model for FederatedInput.
type FederatedInput struct {
	ClientId     string  `json:"client_id"`
	Code         *string `json:"code,omitempty"`
	CodeVerifier *string `json:"code_verifier,omitempty"`
	IdToken      *string `json:"id_token,omitempty"`
	Nonce        string  `json:"nonce"`
	RedirectUri  *string `json:"redirect_uri,omitempty"`
	union        json.RawMessage
}

// FederatedInput0 defines model for FederatedInput.0.
type FederatedInput0 = interface{}

// FederatedInput1 defines model for FederatedInput.1.
type FederatedInput1 = interface{}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Mutation defines model for Mutation.
type Mutation struct {
	BaseVersion int64              `json:"base_version"`
	Data        *Mutation_Data     `json:"data,omitempty"`
	Entity      MutationEntity     `json:"entity"`
	EntityId    openapi_types.UUID `json:"entity_id"`
	Id          openapi_types.UUID `json:"id"`
	Operation   MutationOperation  `json:"operation"`
}

// Mutation_Data defines model for Mutation.Data.
type Mutation_Data struct {
	union json.RawMessage
}

// MutationEntity defines model for Mutation.Entity.
type MutationEntity string

// MutationOperation defines model for Mutation.Operation.
type MutationOperation string

// MutationOutcome defines model for MutationOutcome.
type MutationOutcome struct {
	Code       *string                  `json:"code,omitempty"`
	Current    *MutationOutcome_Current `json:"current,omitempty"`
	Message    *string                  `json:"message,omitempty"`
	MutationId openapi_types.UUID       `json:"mutation_id"`
	Status     MutationOutcomeStatus    `json:"status"`
	Version    *int64                   `json:"version,omitempty"`
}

// MutationOutcome_Current defines model for MutationOutcome.Current.
type MutationOutcome_Current struct {
	union json.RawMessage
}

// MutationOutcomeStatus defines model for MutationOutcome.Status.
type MutationOutcomeStatus string

// PaginatedSessionsResponse defines model for PaginatedSessionsResponse.
type PaginatedSessionsResponse struct {
	HasMore    *bool             `json:"has_more,omitempty"`
	NextCursor *string           `json:"next_cursor,omitempty"`
	Sessions   *[]SessionSummary `json:"sessions,omitempty"`
}

// PaginatedSolvesResponse defines model for PaginatedSolvesResponse.
type PaginatedSolvesResponse struct {
	HasMore    *bool    `json:"has_more,omitempty"`
	NextCursor *string  `json:"next_cursor,omitempty"`
	Solves     *[]Solve `json:"solves,omitempty"`
}

// PasswordCredentials defines model for PasswordCredentials.
type PasswordCredentials struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RefreshToken defines model for RefreshToken.
type RefreshToken struct {
	RefreshToken string `json:"refresh_token"`
}

// Session defines model for Session.
type Session struct {
	Archived  bool               `json:"archived"`
	DeletedAt *time.Time         `json:"deleted_at,omitempty"`
	EndedAt   *time.Time         `json:"ended_at,omitempty"`
	Event     Event              `json:"event"`
	Id        openapi_types.UUID `json:"id"`
	Kind      SessionKind        `json:"kind"`
	Name      string             `json:"name"`
	StartedAt time.Time          `json:"started_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	Version   int64              `json:"version"`
}

// SessionKind defines model for Session.Kind.
type SessionKind string

// SessionInput defines model for SessionInput.
type SessionInput struct {
	Archived  bool               `json:"archived"`
	EndedAt   *time.Time         `json:"ended_at,omitempty"`
	Event     Event              `json:"event"`
	Id        openapi_types.UUID `json:"id"`
	Kind      SessionInputKind   `json:"kind"`
	Name      string             `json:"name"`
	StartedAt time.Time          `json:"started_at"`
}

// SessionInputKind defines model for SessionInput.Kind.
type SessionInputKind string

// SessionSummary defines model for SessionSummary.
type SessionSummary struct {
	Archived   *bool               `json:"archived,omitempty"`
	EndedAt    *time.Time          `json:"ended_at,omitempty"`
	Event      *string             `json:"event,omitempty"`
	Id         *openapi_types.UUID `json:"id,omitempty"`
	Kind       *string             `json:"kind,omitempty"`
	Name       *string             `json:"name,omitempty"`
	SolveCount *int                `json:"solve_count,omitempty"`
	StartedAt  *time.Time          `json:"started_at,omitempty"`
}

// SnapshotRequest defines model for SnapshotRequest.
type SnapshotRequest struct {
	// AfterId Keyset position for the current entity. Zero UUID for the first page of each entity.
	AfterId *openapi_types.UUID `json:"after_id,omitempty"`

	// Cursor Change-log watermark. 0 on the first page; echo the response cursor on subsequent pages.
	Cursor   *int64                 `json:"cursor,omitempty"`
	Device   Device                 `json:"device"`
	Entity   *SnapshotRequestEntity `json:"entity,omitempty"`
	PageSize *int                   `json:"page_size,omitempty"`
}

// SnapshotRequestEntity defines model for SnapshotRequest.Entity.
type SnapshotRequestEntity string

// SnapshotResponse defines model for SnapshotResponse.
type SnapshotResponse struct {
	// Cursor Stable change-log watermark to use as the initial sync cursor once bootstrap completes.
	Cursor      int64                       `json:"cursor"`
	HasMore     bool                        `json:"has_more"`
	NextAfterId *openapi_types.UUID         `json:"next_after_id,omitempty"`
	NextEntity  *SnapshotResponseNextEntity `json:"next_entity,omitempty"`
	Sessions    *[]Session                  `json:"sessions,omitempty"`
	Solves      *[]Solve                    `json:"solves,omitempty"`
}

// SnapshotResponseNextEntity defines model for SnapshotResponse.NextEntity.
type SnapshotResponseNextEntity string

// Solve defines model for Solve.
type Solve struct {
	DeletedAt  *time.Time          `json:"deleted_at,omitempty"`
	DurationMs int64               `json:"duration_ms"`
	Event      Event               `json:"event"`
	Id         openapi_types.UUID  `json:"id"`
	Penalty    SolvePenalty        `json:"penalty"`
	Scramble   string              `json:"scramble"`
	SessionId  *openapi_types.UUID `json:"session_id,omitempty"`
	SolvedAt   time.Time           `json:"solved_at"`
	UpdatedAt  time.Time           `json:"updated_at"`
	Version    int64               `json:"version"`
}

// SolvePenalty defines model for Solve.Penalty.
type SolvePenalty string

// SolveInput defines model for SolveInput.
type SolveInput struct {
	DurationMs int64               `json:"duration_ms"`
	Event      Event               `json:"event"`
	Id         openapi_types.UUID  `json:"id"`
	Penalty    SolveInputPenalty   `json:"penalty"`
	Scramble   string              `json:"scramble"`
	SessionId  *openapi_types.UUID `json:"session_id,omitempty"`
	SolvedAt   time.Time           `json:"solved_at"`
}

// SolveInputPenalty defines model for SolveInput.Penalty.
type SolveInputPenalty string

// StatsResponse defines model for StatsResponse.
type StatsResponse struct {
	Ao100        *int64  `json:"ao100,omitempty"`
	Ao12         *int64  `json:"ao12,omitempty"`
	Ao5          *int64  `json:"ao5,omitempty"`
	Ao50         *int64  `json:"ao50,omitempty"`
	CountedCount int64   `json:"counted_count"`
	DnfCount     int64   `json:"dnf_count"`
	MaxMs        int64   `json:"max_ms"`
	MeanMs       float64 `json:"mean_ms"`
	MinMs        int64   `json:"min_ms"`
	StddevMs     float64 `json:"stddev_ms"`
	TotalCount   int64   `json:"total_count"`
	TotalMs      int64   `json:"total_ms"`
}

// Status defines model for Status.
type Status struct {
	Status string `json:"status"`
}

// SyncRequest defines model for SyncRequest.
type SyncRequest struct {
	Cursor    int64      `json:"cursor"`
	Device    Device     `json:"device"`
	Limit     *int       `json:"limit,omitempty"`
	Mutations []Mutation `json:"mutations"`
}

// SyncResponse defines model for SyncResponse.
type SyncResponse struct {
	Changes    []Change          `json:"changes"`
	HasMore    bool              `json:"has_more"`
	NextCursor int64             `json:"next_cursor"`
	Outcomes   []MutationOutcome `json:"outcomes"`
}

// User defines model for User.
type User struct {
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"email_verified"`
	Id            openapi_types.UUID  `json:"id"`
	UserRole      UserUserRole        `json:"user_role"`
}

// UserUserRole defines model for User.UserRole.
type UserUserRole string

// Provider defines model for Provider.
type Provider string

// StatsFrom defines model for StatsFrom.
type StatsFrom = time.Time

// StatsInterval defines model for StatsInterval.
type StatsInterval string

// StatsTo defines model for StatsTo.
type StatsTo = time.Time

// GetAdminErrorStatsParams defines parameters for GetAdminErrorStats.
type GetAdminErrorStatsParams struct {
	From     *StatsFrom                        `form:"from,omitempty" json:"from,omitempty"`
	To       *StatsTo                          `form:"to,omitempty" json:"to,omitempty"`
	Interval *GetAdminErrorStatsParamsInterval `form:"interval,omitempty" json:"interval,omitempty"`
}

// GetAdminErrorStatsParamsInterval defines parameters for GetAdminErrorStats.
type GetAdminErrorStatsParamsInterval string

// GetAdminRequestTypeStatsParams defines parameters for GetAdminRequestTypeStats.
type GetAdminRequestTypeStatsParams struct {
	From     *StatsFrom                              `form:"from,omitempty" json:"from,omitempty"`
	To       *StatsTo                                `form:"to,omitempty" json:"to,omitempty"`
	Interval *GetAdminRequestTypeStatsParamsInterval `form:"interval,omitempty" json:"interval,omitempty"`
}

// GetAdminRequestTypeStatsParamsInterval defines parameters for GetAdminRequestTypeStats.
type GetAdminRequestTypeStatsParamsInterval string

// GetAdminRequestStatsParams defines parameters for GetAdminRequestStats.
type GetAdminRequestStatsParams struct {
	From     *StatsFrom                          `form:"from,omitempty" json:"from,omitempty"`
	To       *StatsTo                            `form:"to,omitempty" json:"to,omitempty"`
	Interval *GetAdminRequestStatsParamsInterval `form:"interval,omitempty" json:"interval,omitempty"`
}

// GetAdminRequestStatsParamsInterval defines parameters for GetAdminRequestStats.
type GetAdminRequestStatsParamsInterval string

// ResendVerificationJSONBody defines parameters for ResendVerification.
type ResendVerificationJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// VerifyEmailJSONBody defines parameters for VerifyEmail.
type VerifyEmailJSONBody struct {
	Token string `json:"token"`
}

// FederatedLoginParamsProvider defines parameters for FederatedLogin.
type FederatedLoginParamsProvider string

// LinkFederatedIdentityParamsProvider defines parameters for LinkFederatedIdentity.
type LinkFederatedIdentityParamsProvider string

// ForgotPasswordJSONBody defines parameters for ForgotPassword.
type ForgotPasswordJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// ResetPasswordJSONBody defines parameters for ResetPassword.
type ResetPasswordJSONBody struct {
	NewPassword string `json:"new_password"`
	Token       string `json:"token"`
}

// GetV1SessionsParams defines parameters for GetV1Sessions.
type GetV1SessionsParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetV1SessionsIdSolvesParams defines parameters for GetV1SessionsIdSolves.
type GetV1SessionsIdSolvesParams struct {
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetV1StatsParams defines parameters for GetV1Stats.
type GetV1StatsParams struct {
	Event *string `form:"event,omitempty" json:"event,omitempty"`
}

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody ResendVerificationJSONBody

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody VerifyEmailJSONBody

// FederatedLoginJSONRequestBody defines body for FederatedLogin for application/json ContentType.
type FederatedLoginJSONRequestBody = FederatedInput

// LinkFederatedIdentityJSONRequestBody defines body for LinkFederatedIdentity for application/json ContentType.
type LinkFederatedIdentityJSONRequestBody = FederatedInput

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = PasswordCredentials

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshToken

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody ForgotPasswordJSONBody

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody ResetPasswordJSONBody

// RefreshJSONRequestBody defines body for Refresh for application/json ContentType.
type RefreshJSONRequestBody = RefreshToken

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = PasswordCredentials

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// PostV1SnapshotJSONRequestBody defines body for PostV1Snapshot for application/json ContentType.
type PostV1SnapshotJSONRequestBody = SnapshotRequest

// SynchronizeJSONRequestBody defines body for Synchronize for application/json ContentType.
type SynchronizeJSONRequestBody = SyncRequest

// AsSession returns the union data inside the Change_Data as a Session
func (t Change_Data) AsSession() (Session, error) {
	var body Session
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSession overwrites any union data inside the Change_Data as the provided Session
func (t *Change_Data) FromSession(v Session) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSession performs a merge with any union data inside the Change_Data, using the provided Session
func (t *Change_Data) MergeSession(v Session) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolve returns the union data inside the Change_Data as a Solve
func (t Change_Data) AsSolve() (Solve, error) {
	var body Solve
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolve overwrites any union data inside the Change_Data as the provided Solve
func (t *Change_Data) FromSolve(v Solve) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolve performs a merge with any union data inside the Change_Data, using the provided Solve
func (t *Change_Data) MergeSolve(v Solve) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeleteStub returns the union data inside the Change_Data as a DeleteStub
func (t Change_Data) AsDeleteStub() (DeleteStub, error) {
	var body DeleteStub
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeleteStub overwrites any union data inside the Change_Data as the provided DeleteStub
func (t *Change_Data) FromDeleteStub(v DeleteStub) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeleteStub performs a merge with any union data inside the Change_Data, using the provided DeleteStub
func (t *Change_Data) MergeDeleteStub(v DeleteStub) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Change_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Change_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsFederatedInput0 returns the union data inside the FederatedInput as a FederatedInput0
func (t FederatedInput) AsFederatedInput0() (FederatedInput0, error) {
	var body FederatedInput0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFederatedInput0 overwrites any union data inside the FederatedInput as the provided FederatedInput0
func (t *FederatedInput) FromFederatedInput0(v FederatedInput0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFederatedInput0 performs a merge with any union data inside the FederatedInput, using the provided FederatedInput0
func (t *FederatedInput) MergeFederatedInput0(v FederatedInput0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFederatedInput1 returns the union data inside the FederatedInput as a FederatedInput1
func (t FederatedInput) AsFederatedInput1() (FederatedInput1, error) {
	var body FederatedInput1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFederatedInput1 overwrites any union data inside the FederatedInput as the provided FederatedInput1
func (t *FederatedInput) FromFederatedInput1(v FederatedInput1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFederatedInput1 performs a merge with any union data inside the FederatedInput, using the provided FederatedInput1
func (t *FederatedInput) MergeFederatedInput1(v FederatedInput1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FederatedInput) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["client_id"], err = json.Marshal(t.ClientId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'client_id': %w", err)
	}

	if t.Code != nil {
		object["code"], err = json.Marshal(t.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if t.CodeVerifier != nil {
		object["code_verifier"], err = json.Marshal(t.CodeVerifier)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code_verifier': %w", err)
		}
	}

	if t.IdToken != nil {
		object["id_token"], err = json.Marshal(t.IdToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id_token': %w", err)
		}
	}

	object["nonce"], err = json.Marshal(t.Nonce)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'nonce': %w", err)
	}

	if t.RedirectUri != nil {
		object["redirect_uri"], err = json.Marshal(t.RedirectUri)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'redirect_uri': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *FederatedInput) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["client_id"]; found {
		err = json.Unmarshal(raw, &t.ClientId)
		if err != nil {
			return fmt.Errorf("error reading 'client_id': %w", err)
		}
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &t.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
	}

	if raw, found := object["code_verifier"]; found {
		err = json.Unmarshal(raw, &t.CodeVerifier)
		if err != nil {
			return fmt.Errorf("error reading 'code_verifier': %w", err)
		}
	}

	if raw, found := object["id_token"]; found {
		err = json.Unmarshal(raw, &t.IdToken)
		if err != nil {
			return fmt.Errorf("error reading 'id_token': %w", err)
		}
	}

	if raw, found := object["nonce"]; found {
		err = json.Unmarshal(raw, &t.Nonce)
		if err != nil {
			return fmt.Errorf("error reading 'nonce': %w", err)
		}
	}

	if raw, found := object["redirect_uri"]; found {
		err = json.Unmarshal(raw, &t.RedirectUri)
		if err != nil {
			return fmt.Errorf("error reading 'redirect_uri': %w", err)
		}
	}

	return err
}

// AsSessionInput returns the union data inside the Mutation_Data as a SessionInput
func (t Mutation_Data) AsSessionInput() (SessionInput, error) {
	var body SessionInput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSessionInput overwrites any union data inside the Mutation_Data as the provided SessionInput
func (t *Mutation_Data) FromSessionInput(v SessionInput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSessionInput performs a merge with any union data inside the Mutation_Data, using the provided SessionInput
func (t *Mutation_Data) MergeSessionInput(v SessionInput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolveInput returns the union data inside the Mutation_Data as a SolveInput
func (t Mutation_Data) AsSolveInput() (SolveInput, error) {
	var body SolveInput
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolveInput overwrites any union data inside the Mutation_Data as the provided SolveInput
func (t *Mutation_Data) FromSolveInput(v SolveInput) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolveInput performs a merge with any union data inside the Mutation_Data, using the provided SolveInput
func (t *Mutation_Data) MergeSolveInput(v SolveInput) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Mutation_Data) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Mutation_Data) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSession returns the union data inside the MutationOutcome_Current as a Session
func (t MutationOutcome_Current) AsSession() (Session, error) {
	var body Session
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSession overwrites any union data inside the MutationOutcome_Current as the provided Session
func (t *MutationOutcome_Current) FromSession(v Session) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSession performs a merge with any union data inside the MutationOutcome_Current, using the provided Session
func (t *MutationOutcome_Current) MergeSession(v Session) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSolve returns the union data inside the MutationOutcome_Current as a Solve
func (t MutationOutcome_Current) AsSolve() (Solve, error) {
	var body Solve
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSolve overwrites any union data inside the MutationOutcome_Current as the provided Solve
func (t *MutationOutcome_Current) FromSolve(v Solve) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSolve performs a merge with any union data inside the MutationOutcome_Current, using the provided Solve
func (t *MutationOutcome_Current) MergeSolve(v Solve) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConflictStub returns the union data inside the MutationOutcome_Current as a ConflictStub
func (t MutationOutcome_Current) AsConflictStub() (ConflictStub, error) {
	var body ConflictStub
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConflictStub overwrites any union data inside the MutationOutcome_Current as the provided ConflictStub
func (t *MutationOutcome_Current) FromConflictStub(v ConflictStub) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConflictStub performs a merge with any union data inside the MutationOutcome_Current, using the provided ConflictStub
func (t *MutationOutcome_Current) MergeConflictStub(v ConflictStub) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MutationOutcome_Current) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MutationOutcome_Current) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fzdk9u2Ef9XMGgf6ZPufE4T9clx4tStO/H47HSmnhsNjlxJiEmAAUD5FI/+9w6++AlSpCz5q/aLT+QC",
	"2N3fYrFYLPgexzzLOQOmJF68xzkRJAMFwvx6IfiWJiD035ThBc6J2uAIM5KB/uVfR1jAHwUVkOCFEgVE",
	"WMYbyIhuB6zI8OINXnO+TgFHmOR5Cvg2wmqX616kEpSt8X4f4RtFlHwqeFYO+EcBYleNuNLv6r2vuMiI",
	"wgucEAUPFM0A93b8jCkQW5L2dU79+/oACaxIkeoRNrzQknp53M+E7AZkecX7BlN8uhx7rWeZcybBwPOz",
	"ENxgE3OmgCn9p9YujYminM1+l5zpZ9UwfxWwwgv8l1mF+sy+lTPbmxklARkLmutO8MIOg/zIRjjXRnf5",
	"OMkoMyRGYv0oFzwHoajlcuXwHCNiVIGweD9O1RHOOXXWSxVk8pCcLYZf6NZ4X/ZLhCA785tPMLDK/t94",
	"IzUI12zKsVlJwO9+h9gMHWSpo8i7In4LarwqM1Abnmj6zivNLki1jHnBmj1Spr67rnrT/K9BmDa8UBDs",
	"TSqiCrmMeVJ/XzZtqceJUfLne2720+axV22/bkFsKbzrsT4SK7qFZSFByOXV9WaksI1mD+fJMc3+NrYV",
	"g3eTGazajOeuajOaNcUVSZcJbGkMclIbCVJSziY24ul24jhGoJEttiDoikIyoVHLeOtjdvprI9nSeBu0",
	"qGucXQsKmGIblY7GW9rsnTov7Qz7kvx2neXPxnN3meq6oS0IsoZlUgizNi+zpvklvLhLawyyIruzNjvZ",
	"65P73lEGnPsRC4Jz11f399MaPJza4Hpqg0cjG/StTE1tNCRtSNHgsDF6FES8i84hm3q1y+EJL0ImdQxk",
	"9kk1Q0mhrNMpJd2xWP/HSC433DypvIo0jiLCXG1AhKPehq/Ub0ev4zWBP5VDGu837IPjfFcFacd1jXNH",
	"duigIgu1ubF4hSKhGKRcKv4WWDCMg/ucCpBLykY7jZUAuRno0rxZequLOZO6xx+BCLNr7NDrRe6QLl/L",
	"wNRtCNfmrMFHQ043YkiXTzaEraGrxtg8T5Zkgk+OCyG5aND3azUhyuzVOINfV3jxZlgbHu59dIBOxwIH",
	"qX6CFBTcqOIO72+1STBF1a4+hZw7wBE20UVwHtlWS9oMMouCJiHlaOUS5UzWD1PkEoTSc9VwFBxmC8Jb",
	"+lRP7wApBazzXOeoGsThEtXx7zebF0TKd1wkbsoHrKgQApha5o7Qphrqu+6Xjl1EV0htAGlDRSQVQJId",
	"2hCJCPKNkQR1EVKtjjfrI2SUPQe2Vhu8+P6Q9260DUrK2SqlsTLW0hFwJPhFrifOtNn0AbgbJipIa6OH",
	"JKzNho581i5HMP7Gcx5hVqQp1tNqpHJOJ2iN27CgeidxNIg2pfVeBzfevC6v5gHCPCVK99Yivp4fMkYz",
	"rhmm1klIkjIl1hQEwo9bGYt66kRKsg69azsSm6vw9F2WWvSWkSDnW5fB8y7w6v4KR/jh/UMc4et7jfmj",
	"+0dmrDXJKNMxZr4T9s+Qe3wKiXZjkDxjeWF6JmznVpSmbt0yebuPmm/KRExCBcRqWQiKI/N06Xa+At/u",
	"b6O2VlOqXRsNp556dd7sN0RRchp6yTiLwx03+G/Ys5HnAMClMH6IEHj/AJKqTdfA7I7gsBk5ulDX/y5U",
	"uTq28oFEwtLP8ZCPyCijmTam+cniDGtLo4INR/qxwojzRhshf3QwdmgANITtr4WKeQYTHJSLHz5VnNhY",
	"+w3E/R4zwpkTcyyU1awp96lxDLmCxHgjrT3zZ+y4OHV0WOc3GpqbL8iaMu1inXblS39I0kFyQ+Qy46Ku",
	"oDvOUyDMBmr3alntEroaqSVTR204HUM3RZYRsQvuNAekMXnDs8lS5njHSeIMcpQANlx9IiDRc5KkgSwC",
	"ZISmDauwT0LhSj10rsc230f1UPryYPjiRxiMp1/aPesrv8K1sz3De+3WiE3y0HD9eQIRb+gWkjC6HxT3",
	"AkuOburDo8EjTEM0fjF4S1lSdzMZYYVJsZBC8YwoGgddy+h4Vyoipu5uTr0jGgoCBqJsq2+nooYkUWUh",
	"E/ZSjfhhos19M5uJ5xiTgRxAzC8h58GsJnUJ1bGhnYelV/HhpahKoAfPE6Yj0dWky6b3ZoPISoFY0kAW",
	"6F+wk6BQziXVT9CKC5MNcvEfsqHnBfovCI5ev372U0mxokIqlJM1IL5CQOKNJ8bRYV1W63eTH5veepDy",
	"NXpHFIiMiLcXaI44aw36dwTxhpuHvnIE2U41rSzupFYGs8SywdNAarTMUwwnMQ3V0fsOzdFS0j/HFDM4",
	"jm4HUe+Lo/qUfKPIXQooDugaKa4zgYhIo1rKqA5zkD62qdQbA7rjXEklSI60gvSSPVbHI4K7urkeTg7p",
	"FscBcWzUGzoTPlnUGUwjl0oLGoLp67QZxEMnvBm5t6v+999dz/W/Q9mAsyyUOTCSNnFnnNkkXiGX6h3H",
	"EU7YKox+LEh2l7aXzOv5D9/128qgVYYUaeziy4rQmifKXsd1UWrKqwKA8aFalb3pGu03u/tEdncySwhC",
	"roga2PATfjmfjy2B45dXo0kfjaccO76J5iCZVBaRsNUkel3FMbq0JgMyodwnoxOqdqRKEtiO79yWhU2R",
	"1LbIPqBWzleWNHGp67wUulRspbS6jDVu+my4kGfJwd/sWDx0lNt3uH8gAT8xmk1pRpXzSrbby6aDvQya",
	"n0tmjo99yhMHa+nPbJtH8/nYaMgJVh+7X6u9wbGJfsdz7eo1AqHfpHTliDnBbbZ+ukJ9mv9QWFkOEJVa",
	"aPJ5IOB87apojk58mhf+LK5ngz/2gF+CWAqeNsrO9EMcYaKrosYetjheW6zVBwgevkqIC0HV7kZj4c7N",
	"TPmRrpWqfj31cvzzP6/8xQwjcKtUaaNUbu9IULbi3a2b7hWYorEOsCLEV6uUMnhg98V6l7YRnNE/SbmZ",
	"f1LcwSuagUD2pNFs0xRVWmG4eqnnCnr84lktjlvgy4v5xdwdajGSU7zADy8uL+Ym06w2RtjZxhxNzlJq",
	"9yBrW0taHlM9S/ACP9cvW5dLrubzk10tccejgbslLwSPQUpEJSKGRU2iyFoaj7yTCjJ8q595OUz9S68g",
	"L83bTyLJjb6GEAMiLEH6aFUf/iEidPpD87SP8KP5w77uS37LWzg9WthezsysmZlazJkpJ5C96vgFVPt6",
	"TtS44tVzaFiRzKorWftoHPErPpq0vJGliwjOhllbBQHwnpi5Z7CTILYgkNEsMgGKRHc7ZO+o7CN8PZ/3",
	"DdhBUVNfTqKeZCHetxkc617tjanK8Abk3GzIfri7PHPQgpq3bM4NVnO0AF6PbcGyAczcj6Bqh0x0KL8A",
	"rbuK6AdlDfGg6juF0f+vU7ijiIBhOBo/cdeCFzkkZgK7N2Yh/9rmsRNutDF9M6RSCSHvsl4LWOsIDomm",
	"PWl/kxIFLN59HTZUqM3MhNS6U7DnZzmXwdBKv//NBN6xr3By6vmRJ7tJEB25MwmWVQTC/n37Qvq+Y1JX",
	"JzMpl3cYcEa+egm924DagEBcIMaVOcFxV28Q3FOp7OJ19cMxYaKGMgis2Svt+oE1kO5+dho/DaIjq1T6",
	"qlPGAHhCn1C7NRO6/q41g/yO08WIhhrFArSXmOoKhlFb+brd2Xv/gYV9P3plle9zvjYXWqa59PILD/vb",
	"47EfUm6rCvnzgraxW/eoHuOqTzVjU8rejoL9OWVvK9UmZSnqV4D+dTer4gVEWj+QnB2hsYtpAEAzC/th",
	"c5P0HLoOVT9+pdPt4ammG1/zQg3Cpd+fB69GveexM8N1gsxKigRsuZkfw2L7MtTZios1H5D/qXnvDetb",
	"vHeGeG8kUgIkqOHg/PQ4da4PTqqBjqZFgdGhG4eflSvzunZFWh8hLHQV3UM2YAk+F2/10bB4yVV9QbG+",
	"UH7KME7AmkoFYggsR/GZxQIfw03WcwjI3RtCfxRQTJ8yJwItg6ogr4uVvQb8uPxGxuFV2dEi22OCZGE+",
	"T7Aq0nQ31S4nhKOOQ11e1JcEfGLrhl9LZ3pnmrHuGw3dcxY7vF8FP4YuSohn9aUsLwL6ad7dP9PUDH8g",
	"4Nj4r7MOdU3tXCnKDwCjXtjbZ6m/XfpLdd1tbeiDirY6pv5NxW55UrhlWVTRaVoGLOdMSfdfIgzGHY7Y",
	"r3ay9WHGYUSkv8yBn1Opqj5y3y1uQzR7T5P9rKqePgzXM3d/sAe25idEaTL48dAD5SX76Ku1heYVzGFL",
	"MLQfZAe2B12P4oOogEX4b0L1BjUvuNR24OnO4z/bl2k+cizaudURKgVxNEdCUjavLnGYz3KVQPjPYw3M",
	"xfD5XsjifXn4pzH4ZuFxSJeKKCoVjY818F9A2W/nyLKnSpNarb3mfFOWa8G5bLlWV/qx7bhefBnQu69Z",
	"RL4Y0exwuUhAmGPRjCt/Q0l+mUehBvzbvW0htn6OFCJ1dX5yMTMWcgH3RN+huoh5pj928L8BAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
