// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"
	"time"
)

const getOverviewStats = `-- name: GetOverviewStats :one
WITH user_stats AS (
    SELECT
        COUNT(*)::bigint AS total_users,
        COUNT(*) FILTER (WHERE email_verified_at IS NOT NULL)::bigint AS verified_users,
        COUNT(*) FILTER (WHERE created_at >= now() - interval '24 hours')::bigint AS new_users_24h,
        COUNT(*) FILTER (WHERE created_at >= now() - interval '7 days')::bigint AS new_users_7d,
        COUNT(*) FILTER (WHERE created_at >= now() - interval '30 days')::bigint AS new_users_30d
    FROM users
),
active_stats AS (
    SELECT
        COUNT(DISTINCT user_id) FILTER (WHERE last_seen_at >= now() - interval '24 hours')::bigint AS active_users_24h,
        COUNT(DISTINCT user_id) FILTER (WHERE last_seen_at >= now() - interval '7 days')::bigint AS active_users_7d,
        COUNT(DISTINCT user_id) FILTER (WHERE last_seen_at >= now() - interval '30 days')::bigint AS active_users_30d,
        COUNT(*)::bigint AS total_devices
    FROM devices
)
SELECT
    u.total_users,
    u.verified_users,
    u.new_users_24h,
    u.new_users_7d,
    u.new_users_30d,
    a.active_users_24h,
    a.active_users_7d,
    a.active_users_30d,
    a.total_devices,
    (SELECT COUNT(*)::bigint FROM cube_sessions) AS total_sessions,
    (SELECT COUNT(*)::bigint FROM solves) AS total_solves
FROM user_stats u, active_stats a
`

type GetOverviewStatsRow struct {
	TotalUsers     int64 `json:"total_users"`
	VerifiedUsers  int64 `json:"verified_users"`
	NewUsers24h    int64 `json:"new_users_24h"`
	NewUsers7d     int64 `json:"new_users_7d"`
	NewUsers30d    int64 `json:"new_users_30d"`
	ActiveUsers24h int64 `json:"active_users_24h"`
	ActiveUsers7d  int64 `json:"active_users_7d"`
	ActiveUsers30d int64 `json:"active_users_30d"`
	TotalDevices   int64 `json:"total_devices"`
	TotalSessions  int64 `json:"total_sessions"`
	TotalSolves    int64 `json:"total_solves"`
}

func (q *Queries) GetOverviewStats(ctx context.Context) (GetOverviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getOverviewStats)
	var i GetOverviewStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.VerifiedUsers,
		&i.NewUsers24h,
		&i.NewUsers7d,
		&i.NewUsers30d,
		&i.ActiveUsers24h,
		&i.ActiveUsers7d,
		&i.ActiveUsers30d,
		&i.TotalDevices,
		&i.TotalSessions,
		&i.TotalSolves,
	)
	return i, err
}

const listErrorStats = `-- name: ListErrorStats :many
SELECT
    CASE
        WHEN $1::text = 'day' THEN date_trunc('day', bucket_hour)
        ELSE bucket_hour
    END::timestamptz AS bucket,
    method,
    route,
    status_code,
    COALESCE(SUM(request_count), 0)::bigint AS request_count
FROM request_stats_hourly
WHERE bucket_hour >= $2
  AND bucket_hour < $3
  AND status_code >= 400
GROUP BY 1, method, route, status_code
ORDER BY 1, request_count DESC, method, route, status_code
`

type ListErrorStatsParams struct {
	Interval string    `json:"interval"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

type ListErrorStatsRow struct {
	Bucket       time.Time `json:"bucket"`
	Method       string    `json:"method"`
	Route        string    `json:"route"`
	StatusCode   int32     `json:"status_code"`
	RequestCount int64     `json:"request_count"`
}

func (q *Queries) ListErrorStats(ctx context.Context, arg ListErrorStatsParams) ([]ListErrorStatsRow, error) {
	rows, err := q.db.Query(ctx, listErrorStats, arg.Interval, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListErrorStatsRow{}
	for rows.Next() {
		var i ListErrorStatsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Method,
			&i.Route,
			&i.StatusCode,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestStats = `-- name: ListRequestStats :many
SELECT
    CASE
        WHEN $1::text = 'day' THEN date_trunc('day', bucket_hour)
        ELSE bucket_hour
    END::timestamptz AS bucket,
    COALESCE(SUM(request_count), 0)::bigint AS request_count,
    COALESCE(SUM(CASE WHEN status_code >= 200 AND status_code < 300 THEN request_count ELSE 0 END), 0)::bigint AS status_2xx,
    COALESCE(SUM(CASE WHEN status_code >= 300 AND status_code < 400 THEN request_count ELSE 0 END), 0)::bigint AS status_3xx,
    COALESCE(SUM(CASE WHEN status_code >= 400 AND status_code < 500 THEN request_count ELSE 0 END), 0)::bigint AS status_4xx,
    COALESCE(SUM(CASE WHEN status_code >= 500 THEN request_count ELSE 0 END), 0)::bigint AS status_5xx,
    COALESCE(SUM(total_duration_ms), 0)::bigint AS total_duration_ms,
    COALESCE(MAX(max_duration_ms), 0)::bigint AS max_duration_ms
FROM request_stats_hourly
WHERE bucket_hour >= $2 AND bucket_hour < $3
GROUP BY 1
ORDER BY 1
`

type ListRequestStatsParams struct {
	Interval string    `json:"interval"`
	FromTime time.Time `json:"from_time"`
	ToTime   time.Time `json:"to_time"`
}

type ListRequestStatsRow struct {
	Bucket          time.Time `json:"bucket"`
	RequestCount    int64     `json:"request_count"`
	Status2xx       int64     `json:"status_2xx"`
	Status3xx       int64     `json:"status_3xx"`
	Status4xx       int64     `json:"status_4xx"`
	Status5xx       int64     `json:"status_5xx"`
	TotalDurationMs int64     `json:"total_duration_ms"`
	MaxDurationMs   int64     `json:"max_duration_ms"`
}

func (q *Queries) ListRequestStats(ctx context.Context, arg ListRequestStatsParams) ([]ListRequestStatsRow, error) {
	rows, err := q.db.Query(ctx, listRequestStats, arg.Interval, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRequestStatsRow{}
	for rows.Next() {
		var i ListRequestStatsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.RequestCount,
			&i.Status2xx,
			&i.Status3xx,
			&i.Status4xx,
			&i.Status5xx,
			&i.TotalDurationMs,
			&i.MaxDurationMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordRequestStat = `-- name: RecordRequestStat :exec
INSERT INTO request_stats_hourly (
    bucket_hour, method, route, status_code, request_count, total_duration_ms, max_duration_ms
) VALUES (
    $1, $2, $3, $4, 1, $5, $5
)
ON CONFLICT (bucket_hour, method, route, status_code) DO UPDATE
SET request_count = request_stats_hourly.request_count + 1,
    total_duration_ms = request_stats_hourly.total_duration_ms + EXCLUDED.total_duration_ms,
    max_duration_ms = GREATEST(request_stats_hourly.max_duration_ms, EXCLUDED.max_duration_ms)
`

type RecordRequestStatParams struct {
	BucketHour      time.Time `json:"bucket_hour"`
	Method          string    `json:"method"`
	Route           string    `json:"route"`
	StatusCode      int32     `json:"status_code"`
	TotalDurationMs int64     `json:"total_duration_ms"`
}

func (q *Queries) RecordRequestStat(ctx context.Context, arg RecordRequestStatParams) error {
	_, err := q.db.Exec(ctx, recordRequestStat,
		arg.BucketHour,
		arg.Method,
		arg.Route,
		arg.StatusCode,
		arg.TotalDurationMs,
	)
	return err
}
