// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCopyRequestErrors implements pgx.CopyFromSource.
type iteratorForCopyRequestErrors struct {
	rows                 []CopyRequestErrorsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyRequestErrors) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyRequestErrors) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Method,
		r.rows[0].Route,
		r.rows[0].StatusCode,
		r.rows[0].Code,
		r.rows[0].Message,
	}, nil
}

func (r iteratorForCopyRequestErrors) Err() error {
	return nil
}

func (q *Queries) CopyRequestErrors(ctx context.Context, arg []CopyRequestErrorsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"request_errors"}, []string{"user_id", "method", "route", "status_code", "code", "message"}, &iteratorForCopyRequestErrors{rows: arg})
}
