// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listSessionsPaginated = `-- name: ListSessionsPaginated :many
SELECT
    cs.id, cs.user_id, cs.name, cs.event, cs.kind, cs.started_at, cs.ended_at,
    cs.archived, cs.version, cs.updated_at, cs.deleted_at,
    (SELECT COUNT(*)::bigint FROM solves s
     WHERE s.user_id = cs.user_id AND s.session_id = cs.id AND s.deleted_at IS NULL
    ) AS solve_count
FROM cube_sessions cs
WHERE cs.user_id = $1
    AND cs.deleted_at IS NULL
    AND (cs.started_at < $2::timestamptz
         OR (cs.started_at = $2::timestamptz AND cs.id < $3::uuid))
ORDER BY cs.started_at DESC, cs.id DESC
LIMIT $4
`

type ListSessionsPaginatedParams struct {
	UserID   uuid.UUID `json:"user_id"`
	BeforeTs time.Time `json:"before_ts"`
	BeforeID uuid.UUID `json:"before_id"`
	LimitVal int32     `json:"limit_val"`
}

type ListSessionsPaginatedRow struct {
	ID         uuid.UUID  `json:"id"`
	UserID     uuid.UUID  `json:"user_id"`
	Name       string     `json:"name"`
	Event      string     `json:"event"`
	Kind       string     `json:"kind"`
	StartedAt  time.Time  `json:"started_at"`
	EndedAt    *time.Time `json:"ended_at"`
	Archived   bool       `json:"archived"`
	Version    int64      `json:"version"`
	UpdatedAt  time.Time  `json:"updated_at"`
	DeletedAt  *time.Time `json:"deleted_at"`
	SolveCount int64      `json:"solve_count"`
}

func (q *Queries) ListSessionsPaginated(ctx context.Context, arg ListSessionsPaginatedParams) ([]ListSessionsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listSessionsPaginated,
		arg.UserID,
		arg.BeforeTs,
		arg.BeforeID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsPaginatedRow{}
	for rows.Next() {
		var i ListSessionsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Event,
			&i.Kind,
			&i.StartedAt,
			&i.EndedAt,
			&i.Archived,
			&i.Version,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SolveCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSolvesForSessionPaginated = `-- name: ListSolvesForSessionPaginated :many
SELECT id, user_id, session_id, duration_ms, penalty, solved_at, scramble, event, version, updated_at, deleted_at
FROM solves
WHERE user_id = $1
    AND session_id = $2
    AND deleted_at IS NULL
    AND (solved_at < $3::timestamptz
         OR (solved_at = $3::timestamptz AND id < $4::uuid))
ORDER BY solved_at DESC, id DESC
LIMIT $5
`

type ListSolvesForSessionPaginatedParams struct {
	UserID    uuid.UUID     `json:"user_id"`
	SessionID uuid.NullUUID `json:"session_id"`
	BeforeTs  time.Time     `json:"before_ts"`
	BeforeID  uuid.UUID     `json:"before_id"`
	LimitVal  int32         `json:"limit_val"`
}

func (q *Queries) ListSolvesForSessionPaginated(ctx context.Context, arg ListSolvesForSessionPaginatedParams) ([]Solf, error) {
	rows, err := q.db.Query(ctx, listSolvesForSessionPaginated,
		arg.UserID,
		arg.SessionID,
		arg.BeforeTs,
		arg.BeforeID,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Solf{}
	for rows.Next() {
		var i Solf
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.DurationMs,
			&i.Penalty,
			&i.SolvedAt,
			&i.Scramble,
			&i.Event,
			&i.Version,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
