// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ChangeLog struct {
	ChangeID   int64           `json:"change_id"`
	UserID     uuid.UUID       `json:"user_id"`
	EntityType string          `json:"entity_type"`
	EntityID   uuid.UUID       `json:"entity_id"`
	Operation  string          `json:"operation"`
	Version    int64           `json:"version"`
	Payload    json.RawMessage `json:"payload"`
	CreatedAt  time.Time       `json:"created_at"`
}

type CubeSession struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Name      string     `json:"name"`
	Event     string     `json:"event"`
	Kind      string     `json:"kind"`
	StartedAt time.Time  `json:"started_at"`
	EndedAt   *time.Time `json:"ended_at"`
	Archived  bool       `json:"archived"`
	Version   int64      `json:"version"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at"`
}

type Device struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Name        string    `json:"name"`
	Platform    string    `json:"platform"`
	FirstSeenAt time.Time `json:"first_seen_at"`
	LastSeenAt  time.Time `json:"last_seen_at"`
}

type Identity struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Provider  string    `json:"provider"`
	Subject   string    `json:"subject"`
	Email     *string   `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type OneTimeToken struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Kind      string     `json:"kind"`
	TokenHash []byte     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type PasswordCredential struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ProcessedMutation struct {
	UserID     uuid.UUID       `json:"user_id"`
	DeviceID   uuid.UUID       `json:"device_id"`
	MutationID uuid.UUID       `json:"mutation_id"`
	Outcome    json.RawMessage `json:"outcome"`
	CreatedAt  time.Time       `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID  `json:"id"`
	FamilyID  uuid.UUID  `json:"family_id"`
	UserID    uuid.UUID  `json:"user_id"`
	TokenHash []byte     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	RevokedAt *time.Time `json:"revoked_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type RequestError struct {
	ID         int64         `json:"id"`
	CreatedAt  time.Time     `json:"created_at"`
	UserID     uuid.NullUUID `json:"user_id"`
	Method     string        `json:"method"`
	Route      string        `json:"route"`
	StatusCode int32         `json:"status_code"`
	Code       string        `json:"code"`
	Message    string        `json:"message"`
}

type RequestStatsHourly struct {
	BucketHour      time.Time `json:"bucket_hour"`
	Method          string    `json:"method"`
	Route           string    `json:"route"`
	StatusCode      int32     `json:"status_code"`
	RequestCount    int64     `json:"request_count"`
	TotalDurationMs int64     `json:"total_duration_ms"`
	MaxDurationMs   int64     `json:"max_duration_ms"`
}

type Solf struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	SessionID  uuid.NullUUID `json:"session_id"`
	DurationMs int64         `json:"duration_ms"`
	Penalty    string        `json:"penalty"`
	SolvedAt   time.Time     `json:"solved_at"`
	Scramble   string        `json:"scramble"`
	Event      string        `json:"event"`
	Version    int64         `json:"version"`
	UpdatedAt  time.Time     `json:"updated_at"`
	DeletedAt  *time.Time    `json:"deleted_at"`
}

type User struct {
	ID              uuid.UUID  `json:"id"`
	Email           string     `json:"email"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	UserRole        string     `json:"user_role"`
}
