// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

type Querier interface {
	AppendChange(ctx context.Context, arg AppendChangeParams) (int64, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) error
	CreateOneTimeToken(ctx context.Context, arg CreateOneTimeTokenParams) error
	CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSession(ctx context.Context, arg DeleteSessionParams) (CubeSession, error)
	DeleteSolve(ctx context.Context, arg DeleteSolveParams) (Solf, error)
	GetIdentityForUserProvider(ctx context.Context, arg GetIdentityForUserProviderParams) (Identity, error)
	GetLiveSession(ctx context.Context, arg GetLiveSessionParams) (CubeSession, error)
	GetOneTimeTokenForUpdate(ctx context.Context, arg GetOneTimeTokenForUpdateParams) (OneTimeToken, error)
	GetPasswordCredentialByEmail(ctx context.Context, lower string) (GetPasswordCredentialByEmailRow, error)
	GetProcessedMutation(ctx context.Context, arg GetProcessedMutationParams) (json.RawMessage, error)
	GetRefreshTokenForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetSessionForUpdate(ctx context.Context, arg GetSessionForUpdateParams) (CubeSession, error)
	GetSolveForUpdate(ctx context.Context, arg GetSolveForUpdateParams) (Solf, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (CubeSession, error)
	InsertSolve(ctx context.Context, arg InsertSolveParams) (Solf, error)
	InvalidateUserOneTimeTokens(ctx context.Context, arg InvalidateUserOneTimeTokensParams) error
	LatestChangeCursor(ctx context.Context, userID uuid.UUID) (int64, error)
	ListChanges(ctx context.Context, arg ListChangesParams) ([]ChangeLog, error)
	MarkOneTimeTokenUsed(ctx context.Context, id uuid.UUID) error
	MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error
	RecordProcessedMutation(ctx context.Context, arg RecordProcessedMutationParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash []byte) error
	SetUserEmailVerified(ctx context.Context, id uuid.UUID) error
	UpdatePasswordCredential(ctx context.Context, arg UpdatePasswordCredentialParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (CubeSession, error)
	UpdateSolve(ctx context.Context, arg UpdateSolveParams) (Solf, error)
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error
	UpsertPasswordCredential(ctx context.Context, arg UpsertPasswordCredentialParams) error
}

var _ Querier = (*Queries)(nil)
