// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshot.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const snapshotSessionsKeyset = `-- name: SnapshotSessionsKeyset :many
SELECT id, user_id, name, event, kind, started_at, ended_at, archived, version, updated_at, deleted_at
FROM cube_sessions
WHERE user_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type SnapshotSessionsKeysetParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) SnapshotSessionsKeyset(ctx context.Context, arg SnapshotSessionsKeysetParams) ([]CubeSession, error) {
	rows, err := q.db.Query(ctx, snapshotSessionsKeyset, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CubeSession{}
	for rows.Next() {
		var i CubeSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Event,
			&i.Kind,
			&i.StartedAt,
			&i.EndedAt,
			&i.Archived,
			&i.Version,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotSolvesKeyset = `-- name: SnapshotSolvesKeyset :many
SELECT id, user_id, session_id, duration_ms, penalty, solved_at, scramble, event, version, updated_at, deleted_at
FROM solves
WHERE user_id = $1 AND id > $2
ORDER BY id
LIMIT $3
`

type SnapshotSolvesKeysetParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) SnapshotSolvesKeyset(ctx context.Context, arg SnapshotSolvesKeysetParams) ([]Solf, error) {
	rows, err := q.db.Query(ctx, snapshotSolvesKeyset, arg.UserID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Solf{}
	for rows.Next() {
		var i Solf
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionID,
			&i.DurationMs,
			&i.Penalty,
			&i.SolvedAt,
			&i.Scramble,
			&i.Event,
			&i.Version,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
