// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const userSolveAoN = `-- name: UserSolveAoN :many
SELECT
    CASE WHEN penalty = 'plus_two' THEN duration_ms + 2000 ELSE duration_ms END AS effective_ms,
    penalty
FROM solves
WHERE user_id = $1
    AND deleted_at IS NULL
    AND ($2::text = '' OR event = $2::text)
ORDER BY solved_at DESC
LIMIT $3
`

type UserSolveAoNParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Event    string    `json:"event"`
	LimitVal int32     `json:"limit_val"`
}

type UserSolveAoNRow struct {
	EffectiveMs interface{} `json:"effective_ms"`
	Penalty     string      `json:"penalty"`
}

func (q *Queries) UserSolveAoN(ctx context.Context, arg UserSolveAoNParams) ([]UserSolveAoNRow, error) {
	rows, err := q.db.Query(ctx, userSolveAoN, arg.UserID, arg.Event, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSolveAoNRow{}
	for rows.Next() {
		var i UserSolveAoNRow
		if err := rows.Scan(&i.EffectiveMs, &i.Penalty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userSolveStats = `-- name: UserSolveStats :one
SELECT
    COUNT(*)::bigint AS total_count,
    COUNT(*) FILTER (WHERE penalty != 'dnf')::bigint AS counted_count,
    COALESCE(MIN(
        CASE WHEN penalty = 'plus_two' THEN duration_ms + 2000 ELSE duration_ms END
    ) FILTER (WHERE penalty != 'dnf'), 0)::bigint AS min_ms,
    COALESCE(MAX(
        CASE WHEN penalty = 'plus_two' THEN duration_ms + 2000 ELSE duration_ms END
    ) FILTER (WHERE penalty != 'dnf'), 0)::bigint AS max_ms,
    COALESCE(AVG(
        CASE WHEN penalty = 'plus_two' THEN duration_ms + 2000 ELSE duration_ms END
    ) FILTER (WHERE penalty != 'dnf'), 0)::float8 AS mean_ms,
    COALESCE(STDDEV_POP(
        CASE WHEN penalty = 'plus_two' THEN duration_ms + 2000 ELSE duration_ms END
    ) FILTER (WHERE penalty != 'dnf'), 0)::float8 AS stddev_ms,
    COALESCE(SUM(
        CASE WHEN penalty = 'plus_two' THEN duration_ms + 2000 ELSE duration_ms END
    ) FILTER (WHERE penalty != 'dnf'), 0)::bigint AS total_ms,
    COUNT(*) FILTER (WHERE penalty = 'dnf')::bigint AS dnf_count
FROM solves
WHERE user_id = $1
    AND deleted_at IS NULL
    AND ($2::text = '' OR event = $2::text)
`

type UserSolveStatsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Event  string    `json:"event"`
}

type UserSolveStatsRow struct {
	TotalCount   int64   `json:"total_count"`
	CountedCount int64   `json:"counted_count"`
	MinMs        int64   `json:"min_ms"`
	MaxMs        int64   `json:"max_ms"`
	MeanMs       float64 `json:"mean_ms"`
	StddevMs     float64 `json:"stddev_ms"`
	TotalMs      int64   `json:"total_ms"`
	DnfCount     int64   `json:"dnf_count"`
}

func (q *Queries) UserSolveStats(ctx context.Context, arg UserSolveStatsParams) (UserSolveStatsRow, error) {
	row := q.db.QueryRow(ctx, userSolveStats, arg.UserID, arg.Event)
	var i UserSolveStatsRow
	err := row.Scan(
		&i.TotalCount,
		&i.CountedCount,
		&i.MinMs,
		&i.MaxMs,
		&i.MeanMs,
		&i.StddevMs,
		&i.TotalMs,
		&i.DnfCount,
	)
	return i, err
}
