// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appendChange = `-- name: AppendChange :one
INSERT INTO change_log (
    user_id, entity_type, entity_id, operation, version, payload
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING change_id
`

type AppendChangeParams struct {
	UserID     uuid.UUID       `json:"user_id"`
	EntityType string          `json:"entity_type"`
	EntityID   uuid.UUID       `json:"entity_id"`
	Operation  string          `json:"operation"`
	Version    int64           `json:"version"`
	Payload    json.RawMessage `json:"payload"`
}

func (q *Queries) AppendChange(ctx context.Context, arg AppendChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendChange,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
		arg.Operation,
		arg.Version,
		arg.Payload,
	)
	var change_id int64
	err := row.Scan(&change_id)
	return change_id, err
}

const deleteSession = `-- name: DeleteSession :one
UPDATE cube_sessions
SET version = version + 1, updated_at = now(), deleted_at = now()
WHERE user_id = $1 AND id = $2 AND version = $3 AND deleted_at IS NULL
RETURNING id, user_id, name, event, kind, started_at, ended_at, archived, version, updated_at, deleted_at
`

type DeleteSessionParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ID      uuid.UUID `json:"id"`
	Version int64     `json:"version"`
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (CubeSession, error) {
	row := q.db.QueryRow(ctx, deleteSession, arg.UserID, arg.ID, arg.Version)
	var i CubeSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Event,
		&i.Kind,
		&i.StartedAt,
		&i.EndedAt,
		&i.Archived,
		&i.Version,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSolve = `-- name: DeleteSolve :one
UPDATE solves
SET version = version + 1, updated_at = now(), deleted_at = now()
WHERE user_id = $1 AND id = $2 AND version = $3 AND deleted_at IS NULL
RETURNING id, user_id, session_id, duration_ms, penalty, solved_at, scramble, event, version, updated_at, deleted_at
`

type DeleteSolveParams struct {
	UserID  uuid.UUID `json:"user_id"`
	ID      uuid.UUID `json:"id"`
	Version int64     `json:"version"`
}

func (q *Queries) DeleteSolve(ctx context.Context, arg DeleteSolveParams) (Solf, error) {
	row := q.db.QueryRow(ctx, deleteSolve, arg.UserID, arg.ID, arg.Version)
	var i Solf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.DurationMs,
		&i.Penalty,
		&i.SolvedAt,
		&i.Scramble,
		&i.Event,
		&i.Version,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, user_id, name, event, kind, started_at, ended_at, archived, version, updated_at, deleted_at FROM cube_sessions
WHERE user_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetLiveSessionParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetLiveSession(ctx context.Context, arg GetLiveSessionParams) (CubeSession, error) {
	row := q.db.QueryRow(ctx, getLiveSession, arg.UserID, arg.ID)
	var i CubeSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Event,
		&i.Kind,
		&i.StartedAt,
		&i.EndedAt,
		&i.Archived,
		&i.Version,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProcessedMutation = `-- name: GetProcessedMutation :one
SELECT outcome FROM processed_mutations
WHERE user_id = $1 AND device_id = $2 AND mutation_id = $3
`

type GetProcessedMutationParams struct {
	UserID     uuid.UUID `json:"user_id"`
	DeviceID   uuid.UUID `json:"device_id"`
	MutationID uuid.UUID `json:"mutation_id"`
}

func (q *Queries) GetProcessedMutation(ctx context.Context, arg GetProcessedMutationParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getProcessedMutation, arg.UserID, arg.DeviceID, arg.MutationID)
	var outcome json.RawMessage
	err := row.Scan(&outcome)
	return outcome, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, user_id, name, event, kind, started_at, ended_at, archived, version, updated_at, deleted_at FROM cube_sessions
WHERE user_id = $1 AND id = $2
FOR UPDATE
`

type GetSessionForUpdateParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetSessionForUpdate(ctx context.Context, arg GetSessionForUpdateParams) (CubeSession, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, arg.UserID, arg.ID)
	var i CubeSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Event,
		&i.Kind,
		&i.StartedAt,
		&i.EndedAt,
		&i.Archived,
		&i.Version,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSolveForUpdate = `-- name: GetSolveForUpdate :one
SELECT id, user_id, session_id, duration_ms, penalty, solved_at, scramble, event, version, updated_at, deleted_at FROM solves
WHERE user_id = $1 AND id = $2
FOR UPDATE
`

type GetSolveForUpdateParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetSolveForUpdate(ctx context.Context, arg GetSolveForUpdateParams) (Solf, error) {
	row := q.db.QueryRow(ctx, getSolveForUpdate, arg.UserID, arg.ID)
	var i Solf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.DurationMs,
		&i.Penalty,
		&i.SolvedAt,
		&i.Scramble,
		&i.Event,
		&i.Version,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO cube_sessions (
    id, user_id, name, event, kind, started_at, ended_at, archived
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, name, event, kind, started_at, ended_at, archived, version, updated_at, deleted_at
`

type InsertSessionParams struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Name      string     `json:"name"`
	Event     string     `json:"event"`
	Kind      string     `json:"kind"`
	StartedAt time.Time  `json:"started_at"`
	EndedAt   *time.Time `json:"ended_at"`
	Archived  bool       `json:"archived"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (CubeSession, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Event,
		arg.Kind,
		arg.StartedAt,
		arg.EndedAt,
		arg.Archived,
	)
	var i CubeSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Event,
		&i.Kind,
		&i.StartedAt,
		&i.EndedAt,
		&i.Archived,
		&i.Version,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertSolve = `-- name: InsertSolve :one
INSERT INTO solves (
    id, user_id, session_id, duration_ms, penalty, solved_at, scramble, event
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, session_id, duration_ms, penalty, solved_at, scramble, event, version, updated_at, deleted_at
`

type InsertSolveParams struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	SessionID  uuid.NullUUID `json:"session_id"`
	DurationMs int64         `json:"duration_ms"`
	Penalty    string        `json:"penalty"`
	SolvedAt   time.Time     `json:"solved_at"`
	Scramble   string        `json:"scramble"`
	Event      string        `json:"event"`
}

func (q *Queries) InsertSolve(ctx context.Context, arg InsertSolveParams) (Solf, error) {
	row := q.db.QueryRow(ctx, insertSolve,
		arg.ID,
		arg.UserID,
		arg.SessionID,
		arg.DurationMs,
		arg.Penalty,
		arg.SolvedAt,
		arg.Scramble,
		arg.Event,
	)
	var i Solf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.DurationMs,
		&i.Penalty,
		&i.SolvedAt,
		&i.Scramble,
		&i.Event,
		&i.Version,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const latestChangeCursor = `-- name: LatestChangeCursor :one
SELECT COALESCE(MAX(change_id), 0)::bigint FROM change_log
WHERE user_id = $1
`

func (q *Queries) LatestChangeCursor(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, latestChangeCursor, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listChanges = `-- name: ListChanges :many
SELECT change_id, user_id, entity_type, entity_id, operation, version, payload, created_at FROM change_log
WHERE user_id = $1 AND change_id > $2
ORDER BY change_id
LIMIT $3
`

type ListChangesParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ChangeID int64     `json:"change_id"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListChanges(ctx context.Context, arg ListChangesParams) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, listChanges, arg.UserID, arg.ChangeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeLog{}
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ChangeID,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.Operation,
			&i.Version,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProcessedMutation = `-- name: RecordProcessedMutation :exec
INSERT INTO processed_mutations (user_id, device_id, mutation_id, outcome)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, device_id, mutation_id) DO NOTHING
`

type RecordProcessedMutationParams struct {
	UserID     uuid.UUID       `json:"user_id"`
	DeviceID   uuid.UUID       `json:"device_id"`
	MutationID uuid.UUID       `json:"mutation_id"`
	Outcome    json.RawMessage `json:"outcome"`
}

func (q *Queries) RecordProcessedMutation(ctx context.Context, arg RecordProcessedMutationParams) error {
	_, err := q.db.Exec(ctx, recordProcessedMutation,
		arg.UserID,
		arg.DeviceID,
		arg.MutationID,
		arg.Outcome,
	)
	return err
}

const updateSession = `-- name: UpdateSession :one
UPDATE cube_sessions
SET name = $3,
    event = $4,
    kind = $5,
    started_at = $6,
    ended_at = $7,
    archived = $8,
    version = version + 1,
    updated_at = now(),
    deleted_at = NULL
WHERE user_id = $1 AND id = $2 AND version = $9
RETURNING id, user_id, name, event, kind, started_at, ended_at, archived, version, updated_at, deleted_at
`

type UpdateSessionParams struct {
	UserID    uuid.UUID  `json:"user_id"`
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	Event     string     `json:"event"`
	Kind      string     `json:"kind"`
	StartedAt time.Time  `json:"started_at"`
	EndedAt   *time.Time `json:"ended_at"`
	Archived  bool       `json:"archived"`
	Version   int64      `json:"version"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (CubeSession, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Event,
		arg.Kind,
		arg.StartedAt,
		arg.EndedAt,
		arg.Archived,
		arg.Version,
	)
	var i CubeSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Event,
		&i.Kind,
		&i.StartedAt,
		&i.EndedAt,
		&i.Archived,
		&i.Version,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSolve = `-- name: UpdateSolve :one
UPDATE solves
SET session_id = $3,
    duration_ms = $4,
    penalty = $5,
    solved_at = $6,
    scramble = $7,
    event = $8,
    version = version + 1,
    updated_at = now(),
    deleted_at = NULL
WHERE user_id = $1 AND id = $2 AND version = $9
RETURNING id, user_id, session_id, duration_ms, penalty, solved_at, scramble, event, version, updated_at, deleted_at
`

type UpdateSolveParams struct {
	UserID     uuid.UUID     `json:"user_id"`
	ID         uuid.UUID     `json:"id"`
	SessionID  uuid.NullUUID `json:"session_id"`
	DurationMs int64         `json:"duration_ms"`
	Penalty    string        `json:"penalty"`
	SolvedAt   time.Time     `json:"solved_at"`
	Scramble   string        `json:"scramble"`
	Event      string        `json:"event"`
	Version    int64         `json:"version"`
}

func (q *Queries) UpdateSolve(ctx context.Context, arg UpdateSolveParams) (Solf, error) {
	row := q.db.QueryRow(ctx, updateSolve,
		arg.UserID,
		arg.ID,
		arg.SessionID,
		arg.DurationMs,
		arg.Penalty,
		arg.SolvedAt,
		arg.Scramble,
		arg.Event,
		arg.Version,
	)
	var i Solf
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionID,
		&i.DurationMs,
		&i.Penalty,
		&i.SolvedAt,
		&i.Scramble,
		&i.Event,
		&i.Version,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (id, user_id, name, platform)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, id) DO UPDATE
SET name = EXCLUDED.name,
    platform = EXCLUDED.platform,
    last_seen_at = now()
`

type UpsertDeviceParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Name     string    `json:"name"`
	Platform string    `json:"platform"`
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Platform,
	)
	return err
}
